### ISSUE TITLE
[Feature Request] - Stream font with diacritics

### ISSUE THREAD

**Issue by TheFantomas** [esx-framework/esx_core#1008]
**Describe the Feature**
As part of updating all translations, it is necessary to stream some custom font with diacritics. It would also be good to have a custom font for Arabic as well and probably for other languages ​​as well.

So I would imagine that if I set the locale to Czech, I will automatically have a different font, the same for Arabic.

**Additional context**
https://github.com/elvodkaa/Fonts-Arabic-FiveM

**Comment by Gellipapa** [comment]
![image](https://github.com/esx-framework/esx_core/assets/22717950/8979d960-2739-436b-8466-3f7cfe726448)

**Comment by TheFantomas** [comment]
> ![image](https://user-images.githubusercontent.com/22717950/258915708-8979d960-2739-436b-8466-3f7cfe726448.png)

So I finally got around to it. To prove that all languages will display diacritics correctly we need a font that supports diacritics.

I would choose Poppins (https://fonts.google.com/specimen/Poppins?query=poppins)

Then we need to convert it to gfx format - I can arrange that. And then we just have to come up with a system. We need two fonts (one special for Arabic).

Any ideas?

**Comment by m-imperfect** [comment]
Great efforts, I see, well done so far but there is a small problem...  
Arabic is not supported by the game engine, as you already know, writing with Arabic letters is not like writing with Latin letters.  
When you write with Latin letters you just put them beside each other to form a word, it's not the same when you write with Arabic letters, as the letters have to be linked to each other in a certain way depending on their position in the word.  
For example, the letter (ع) can be written in three different ways depending on its position, which are:  
- At the beginning: (عـ)
- At the middle: (ـعـ)
- At the end: (ـع)  

Not to mention that Arabic text direction is rtl (right to left) unlike most other locales which use ltr (left to right) text direction.  
From my experience with FiveM and streaming `gfx` stuff, just adding a font doesn't fix the issue with Arabic.  
What to do? well, I've created a script to optimize Arabic sentences to fit and suit the game engine but It's not completed it still needs some enhancements, but it's working just fine (except for some cases that are mentioned in the README).  

For other languages, I already talked about it [here](https://forum.cfx.re/t/support-arabic/5163695/5?u=m_imperfect).  

For more information about the Arabic issue and the script go [here](https://github.com/imperfect-fivem/support-arabic).  
Note: The "cracked" solution that's mentioned is the best result I could get. If you have a way to change the game engine text direction or any other ideas, lmk.  
  
Note: I've already edited the [`locale.lua`](https://github.com/esx-framework/esx_core/blob/1.10.1/%5Bcore%5D/es_extended/locale.lua) file to work around the script, it works just fine but there are some personal use cases in my edit, so... I'll edit it to generalize the edit in a way that doesn't affect the default version of the framework and I'll open a pull request as soon as possible.

**Comment by Gellipapa** [comment]
@TheFantomas Can you handle that?

**Comment by m-imperfect** [comment]
This issue shall be closed. Fonts with diacritics could be easily streamed into gfx using that [tool](https://forum.cfx.re/t/tool-gfx-font-converter/4952616).  
Regarding Arabic support, I've updated the [script](https://forum.cfx.re/t/support-arabic/5163695).  
Anyone could just add:
```lua
client_script '@support-arabic/escaping.lua'
```
to any script so that it supports Arabic.

**Comment by Gellipapa** [comment]
@m-imperfect Hi! Thank you for your response i closed. Thanks.
