### ISSUE TITLE
[Bug + Fix] - esx_menu_default in esx_vehicleshop - Issue

### ISSUE THREAD

**Issue by PabloSchar** [esx-framework/esx_core#1021]
**Describe the bug**
The error occurs when entering the esx_vehicleshop and quickly navigating through the options, generating all the vehicles that you selected, and they cannot be removed. This happens because the addon vehicle allows you to continue navigating the menu while it is being downloaded.

**To Reproduce**
1. Go to 'the point of sale in esx_vehicleshop'
2. Press the key to access the vehicles for sale
3. Move quickly through the vehicle catalog
4. See bug

**Screenshots**
![image](https://user-images.githubusercontent.com/91165563/232901890-4ed83d34-f1fc-41fd-9fbb-269f358d9db9.png)
![image](https://user-images.githubusercontent.com/91165563/232901935-4bb8998f-1c69-48ed-a23e-74317b7d2e7d.png)
https://github.com/esx-framework/esx_vehicleshop/issues/16

**Debug Info (please complete the following information):**
 - OS: Windows
 -  FiveM Artifact 6385
 - ESX Version:1.9.4

**Additional context**
FIX:
The problem is caused by the esx_menu_default. I modified the script and uploaded it for repair.
https://github.com/PabloSchar/esx_menu_default

**Comment by Gellipapa** [comment]
Hi! @PabloSchar Thank you report issue and sent fix. 
Can you show changes? 
We can't see esx_menu_default changes if you push once commit.

Thank you.

**Comment by PabloSchar** [comment]
Just modify the main.lua

**Comment by Gellipapa** [comment]
> @Gellipapa Just modify the main.lua

Thank you for answer, i tested https://github.com/esx-framework/esx_vehicleshop/pull/29 this pr and works perfectly, but thank you for fixes.
