### ISSUE TITLE
[Bug] - esx_multicharacter - Issue

### ISSUE THREAD

**Issue by timonation** [esx-framework/esx_core#1025]
**Describe the bug**

**To Reproduce**
1. Go to config and set Config.Slots = 1

set permissions to extra slots in database. whats the right format from identifier?

when i connect to server i cant create a second character
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/35240334/233737082-b46f067f-e0a0-485b-a2c6-45a5d792365f.png)

**Debug Info (please complete the following information):**
 - OS: ( Windows/Linux)
 -  FiveM Artifact
 - ESX Version: 1.8.5

**Comment by Gellipapa** [comment]
Hi! @timonation I tested and it works perfectly. You should add your license to identifier column. Only number! 
For example: license:12345 you should add only 12345. 

Please check your es_extended config.lua file and search "Identifier" if you find this config properties this is your default identifier else is license.

I hope it's clear.

**Comment by Gellipapa** [comment]
There was no reply so I'm closing the issue probably no further questions/problems.
