### ISSUE TITLE
[Bug] - es_extended

### ISSUE THREAD

**Issue by Te0lexx** [esx-framework/esx_core#1029]
**Describe the bug**
The player seems to be stuck in an infinite loop with a black screen.
**To Reproduce**
1. Install ESX
2. Launch Server
3. Go to Console

**Expected behavior**
The player can play on the server as normal
**Screenshots**
![image](https://user-images.githubusercontent.com/83425458/234336521-a01ec725-7af9-49d2-b7c9-d497b7c7d013.png)

**Debug Info (please complete the following information):**
 - OS: Windows
 - ESX Version: Legacy

**Additional context**
I think this likely occurs because the event doesn't even exist anymore since on the documentation it's not listed anywhere.
Or the event is not defined idk.

**Comment by Mycroft-Studios** [comment]
This is not a bug. This is a user error, install ESX correctly and read the documentation page and it will work

**Comment by Mycroft-Studios** [comment]
also side note.

> I think this likely occurs because the event doesn't even exist anymore since on the documentation it's not listed anywhere.
Or the event is not defined idk.

Completely Wrong.

This issue is with you not installing esx multicharacter correctly, or stopping the resource without actually disabling it (which is done by removing it from the resources)
