### ISSUE TITLE
[Feature Request] - esx_radio - Full rewrite and move to our organization

### ISSUE THREAD

**Issue by TheFantomas** [esx-framework/esx_core#1040]
From my point of view, it would be a good idea to move esx_radio from Benzo's github directly to our github.

In order for this to be implemented, we must first of all rewrite the entire script.

**Comment by Thekuca** [comment]
[Current Status](https://github.com/Thekuca/esx_radio)

**Comment by Gellipapa** [comment]
I don't think we need qb-radio, we can write it ourselves so it went into backlog.
