### ISSUE TITLE
[Bug] - esx_script - Issue

### ISSUE THREAD

**Issue by Tommyraalte** [esx-framework/esx_core#1041]
**Car spawns in ground or stuck in air (freeze)*

wherever I take vehicles out, they regularly float where under the taxi job card dealer and the garage as soon as you take them out they keep freezing or floating a piece of the ground. one citizen is more affected than the other, what can I do about this?

even in the clothing store you occasionally freeze

on the discord of esx framework i read that several cities suffer from it but no solution

No error,s in f8

**Screenshots**

![image](https://user-images.githubusercontent.com/99044646/236830571-47b5301b-90a7-4685-8601-397aedbd604b.png)

**Debug Info (please complete the following information):**
 - OS: Windows
 -  FiveM Artifact  FXServer 6432
 - ESX Version: 1.9.5

**Comment by Gellipapa** [comment]
@Tommyraalte Hi! Thank you for reported issue, please update your core latest version and this solved your problem.  If don't solved problem please reopen issue.

**Comment by Restavratora** [comment]
Hello, in 2024 with the new ESX 1.11.4 I have the same issue, how can I fix it?
