### ISSUE TITLE
[Bug] - es_extended - error using command goto

### ISSUE THREAD

**Issue by XianPT** [esx-framework/esx_core#1051]
**Describe the bug**
Using Command /goto [ID] - If you enter the wrong ID, it gives this error .

**To Reproduce**
1. Using Command /goto [ID] - 
2. If you enter the wrong ID, it gives this error .

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://prnt.sc/nfxHzTuG7xyj)

**Debug Info (please complete the following information):**
 - OS: Windows
 -  FiveM Artifact : 6461
 - ESX Version: 1.9.4

**Comment by XianPT** [comment]
I now notice that all the commands that use the iD give an error if you put in the wrong ID.

**Comment by rdopaa** [comment]
Me too, how i can fix that?

**Comment by Gellipapa** [comment]
#1088 Fixed, thank you all reports.
