### ISSUE TITLE
Missing in SetVehicleProperties

### ISSUE THREAD

**Issue by iSentrie** [esx-framework/esx_core#1054]
1. Issue
```lua
modDoorR = GetVehicleMod(vehicle, 47),
```
https://github.com/esx-framework/esx_core/blob/fca0756c650d5db54e02a88bb74b1d9ac4b15381/%5Bcore%5D/es_extended/client/functions.lua#LL741C9-L741C18

This is never used in `SetVehicleProperties`
Also missing:
`VMT_DOOR_L` = 46.
`VMT_LIGHTBAR` = 49,
veh mod variation = `GetVehicleModVariation(vehicle, 23)` `Only used for wheels(ModType = 23/24) Returns true if the wheels are custom wheels`
bulletproof tyres = `GetVehicleTyresCanBurst(vehicle)`
roof livery = `GetVehicleRoofLivery(vehicle)`

2. From what I tested long time ago, if you store vehicle with windows rolled down they will count as broken and wrong properties will be saved on those. Solution is to roll up windows on `GetVehicleProperties`

3. Extras ID's goes more than 12, might be 15~ now, not sure.
4. Windows... Preference wise, but `SmashVehicleWindow(vehicle, tonumber(k))` every time player gets a vehicle is weird, I would suggest just `RemoveVehicleWindow`

**Comment by Gellipapa** [comment]
Hi! @iSentrie 

1. 46 index is windows, and 47 is unknow. I can't find these indexes and return only -1. (https://github.com/Konijima/WikiFive/wiki/Vehicle-Mod-Types, https://wiki.rage.mp/index.php?title=Vehicle_Mods)

2. GetVehicleModVariation native only use wheels and we use correct.

3.Extra IDs i found example use 20.

**Comment by Gellipapa** [comment]
We fixed all issue in  1.10.1 , thank you for report issues.
