### ISSUE TITLE
[Bug] [Feature Request] - Weapons Tints not saved properly

### ISSUE THREAD

**Issue by MehdiBenbahri** [esx-framework/esx_core#1055]
Well, i maybe lied in the first place when selecting the issue type. ESX code doesn't support weapon tints correctly. Since Mk II weapons got 33 differents tints ( source : https://docs.fivem.net/natives/?_0x50969B9B89ED5738) ESX core seems to be not able to save the player  loadout correctly.
Then, when you call  xPlayer.setWeaponTint("weapon_snspistol_mk2", 10) you will not see any error or any change. If you force the Tint display in client side, it's just visual, but now, after i think 5 years of Mk II weapons, ESX should be able to support them...

I don't exactly find the code that ignore the player loadout, but if you see carefully, even the locale files support only 8 tints. This proove that Mk II Weapons was forgotten.

We should add Livery and Livery color for weapons too... I'm testing if weapon components are working well too, but i have no hope.

**Comment by iSentrie** [comment]
They might be added earlier, but as always community work is being closed without any reasons...
https://github.com/esx-framework/esx_core/pull/754

**Comment by MehdiBenbahri** [comment]
> These might be added earlier, but often community work is being closed without any reasons... #754

I got problem for Los Santos Drugs Wars weapon DLC too, but this is different here, MK 2 weapon should be supported :(
Then we will wait for the [PreacherDev](https://github.com/PreacherDev) commit to be accepted *-*

**Comment by iSentrie** [comment]
As I mentioned, they closed it. Same as a lot of other cool stuff.
