### ISSUE TITLE
[Bug] - es_extended - problem sync vehicle

### ISSUE THREAD

**Issue by Edvesse** [esx-framework/esx_core#1059]
Hello,

I have a considerable problem with the appearance of vehicles. When players make their vehicles appear, if they move too far away, the vehicles disappear. I've tried using ESX.OneSync.SpawnVehicle but sometimes it doesn't appear, sometimes it does. What's more, vehicle properties usually only appear after a few seconds, and sometimes some players lose certain vehicle properties.

Would you have a solution for me? 

I'm running ESX 1.9.4 with onesync infinity

**Comment by Edvesse** [comment]
Hello, Any help ? I've tried all possible formulas, via server, via client, with SetEntityDistanceCullingRadius, nothing works, the vehicles always disappear if you're too far away from them

**Comment by Mycroft-Studios** [comment]
your esx is not 1.9.4. also SetEntityDistanceCullingRadius Should NEVER be used. and every you are experincing is Literally what onesync is and is intended

**Comment by Mycroft-Studios** [comment]
> My version of es extended are 1.9.4, 

it is not. and you do not prevent it, that is literally what onesync is. it limits the clients area to a 424m radius, the client has no knowledge of anything outside of that. If server-sided vehicles are somehow despawning in 1.9.4, you have an external script that is interfering with them.

**Comment by Mycroft-Studios** [comment]
also, anything spawned on the client will ALWAYS disappear, the only way for persistence is ESX.OneSync.SpawnVehicle, since they are owned and spawned on the server.

As soon as the client goes 424m away from the vehicle, it no longer knows of its existence, and unless theres another player within 424m to take ownership, it gets deleted because it has no owner

**Comment by Ricko0o** [comment]
Not meaning to interupt, but did you check the LOD distances in the vehicles.meta of each vehicle? Increasing those numbers will, in most cases, solve that issue

**Comment by Gellipapa** [comment]
@Mycroft-Studios @Edvesse Hi! What a status or result? Please tell me.

**Comment by Mycroft-Studios** [comment]
> @Mycroft-Studios @Edvesse Hi! What a status or result? Please tell me.

This seems to be from using a very old lscustoms, or, just really bad connection

**Comment by Gellipapa** [comment]
@Mycroft-Studios It's okey, thank you for response.
