### ISSUE TITLE
[Bug] - esx_script - Issue

### ISSUE THREAD

**Issue by newbialywhodis** [esx-framework/esx_core#1062]
**Describe the bug**
There is an issue on creating new character. There is no way to rotate the camera (/skin, clotheshops etc works good)

**To Reproduce**
1. Make new character
2. Try to rotate camera

**Expected behavior**
The camera should rotate

**Screenshots**
X

**Debug Info (please complete the following information):**
 - OS: Linux ubuntu
 -  FiveM Artifact: build 2802
 - ESX Version: 1.9.4

**Additional context**

**Comment by FUst1ke** [comment]
esx_multichar, or esx_identity does not have a feature to rotate camera. Only when you are making your character's appearance

**Comment by Gellipapa** [comment]
Not bug, this is new feature.

**Comment by Gellipapa** [comment]
@newbialywhodis Sorry, me misunderstanding has been corrected thanks for the report.

https://github.com/esx-framework/esx_core/pull/1104/commits/4bb98a8e0faad70672813e372565c97381d15c49
