### ISSUE TITLE
[Bug] ESX Cannot Connect to your database

### ISSUE THREAD

**Issue by 2749773995** [esx-framework/esx_core#1076]
Everything is fine at first, I can enter the server normally.
I don't know when it started, I can't enter the server, it prompts me：[ESX Multicharacter] ESX Cannot Connect to your database. Please make sure it is correctly configured in your server.cfg
But everything is fine in my server.cfg
![U)NWS NUD~GS8FH1H$E~CTJ](https://github.com/esx-framework/esx_core/assets/104758168/0222cc05-d80f-4cbd-9ce2-9820c6b0b953)

Here is my server.cfg file
[server.txt](https://github.com/esx-framework/esx_core/files/11858760/server.txt)

ESX Version:1.9.4

**Comment by Mycroft-Studios** [comment]
this is not a bug ,this is a user error, check your server console for errors and use the discord for support

**Comment by KuBa000001** [comment]
i have same problem do you know how to fix it?
