### ISSUE TITLE
[Bug] esx_society (society already registered, name: police)

### ISSUE THREAD

**Issue by GreenShot16** [esx-framework/esx_core#1120]
Hello, i have the problem when i restart my server i become follow errors in the console:

[  script:esx_society] [WARNING] society already registered, name: ambulance
[  script:esx_society] [WARNING] society already registered, name: cardealer
[  script:esx_society] [WARNING] society already registered, name: police
[  script:esx_society] [WARNING] society already registered, name: realestate

i using es_extended 1.10.1 and all SQL are corectly insert in the database

thanks for help!

**Comment by Gellipapa** [comment]
@GreenShot16 Hi! I failed to cause the problem by installing a completely new server. You might have a problem where it wants to register the society more than once but I have not been able to reproduce it. This is a warning so the script will still work. Try to completely reinstall your server database and delete everything else.

**Comment by GreenShot16** [comment]
@Gellipapa i upgrade to esx legacy and have create a new database, and now i have the error codes, all basic scripts (esx_addonaccount, esx_identity, esx_society etc. are version over 1.9 and for esx legacy)

**Comment by Gellipapa** [comment]
@GreenShot16 Hi! Can you any photo for error message?

**Comment by GreenShot16** [comment]
@Gellipapa https://ibb.co/DfdXZP9

**Comment by Gellipapa** [comment]
@GreenShot16 Thank you photo. I think you should try stopping jobs_creator and starting the server. So take it out of server.cfg temporarily.

**Comment by thesysadmindev** [comment]
This is expected, as jobs_creator assumes management of player societies. It's not a bug as jobs_creator registers the society before esx_society does.

If you really don't want the error to appear you can either:
a) Suppress the error message, or
b) Tell jobs_creator not to register the society, or
c) Tell esx_society not to register the society.

Note that (a) and (c) require modifications to core resources which is not supported.

**Comment by Gellipapa** [comment]
No feedback so the issue has been closed.
