### ISSUE TITLE
[Bug] - es_extended- commands are forced to validate

### ISSUE THREAD

**Issue by iSentrie** [esx-framework/esx_core#1126]
As we can see here if no value is set it supposed to be 5, however in latest framework version it doesn't work anymore and user is forced to put an argument there.

https://github.com/esx-framework/esx_core/blob/2c5b5c92d87c43278c342d279bd958a56c7d4202/%5Bcore%5D/es_extended/server/commands.lua#L113-L114

**To Reproduce**
1. Type /dv
2. Will get message of invalid argument

**Expected behavior**
At this particular example it should delete vehicles in radius of 5

**Debug Info:**
 - OS: Win
 - FiveM Artifact 6576
 - ESX Version: 1.10.1

**Comment by TheFantomas** [comment]
Fixed in dev branch. If you can try it it will be good <3

1.10.2 will be released soon i guess :D

**Comment by Gellipapa** [comment]
@iSentrie Hi! Thanks for the report, but this has been fixed and will work fine in the next release.
