### ISSUE TITLE
[Scam] - Benzo - ESX Team member is scamming other peoples.

### ISSUE THREAD

**Issue by soniXx123** [esx-framework/esx_core#1141]
This is a bug report for your Team. A Team member is scamming other people's cash! be careful!!!

https://streamable.com/c79c4t

**Comment by Cyzxin** [comment]
1. Benzo is no longer part of the ESX team, what he may engage in during his spare time is out of ESX's control. 

2. What makes you think github is the place to do this? There's a discord with more active support and more people would see your posts or whatever. Posting this on github seems quite stupid as people don't browse github for "gossip" on FiveM "scammers"

**Comment by Gellipapa** [comment]
> 

@Cyzxin Correct answer.
