### ISSUE TITLE
[Bug] - esx_vehicleshop/es_extended ?

### ISSUE THREAD

**Issue by MauriceHandwerker** [esx-framework/esx_core#1142]
**Describe the bug**
When I try getting a vehicle from the database I get this error :
![image](https://github.com/esx-framework/esx_core/assets/66009198/603c0dfe-1814-420a-b203-0cc42cbf85ee)

**To Reproduce**
1. have newest Linux Artifact, es_extended and esx_vehicle shop installed
2. Get vehicle from garage like police garage ...
3. See error

**Expected behavior**
Car should spawn.

**Screenshots**
see above

**Debug Info (please complete the following information):**
 - OS: Linux
 -  FiveM Artifact: Linux 6594
 - ESX Version: 1.10.1
 - esx_vehicleshop version: 02.08.2023

**Comment by Gellipapa** [comment]
@MauriceHandwerker Hi! Thanks for reporting the problem I will check it soon.

**Comment by MauriceHandwerker** [comment]
Ok I temporally fixed the error. 

es_extended/client/functions.lua : 834
```lua
if props.driftTyresEnabled then          
        --SetDriftTyresEnabled(vehicle, false)
    end
```
I just commented the line. It looks like that the native is broken of Linux Artifact version 6594.

**Comment by Gellipapa** [comment]
> Ok I temporally fixed the error.
> 
> es_extended/client/functions.lua : 834
> 
> ```lua
> if props.driftTyresEnabled then          
>         --SetDriftTyresEnabled(vehicle, false)
>     end
> ```
> 
> I just commented the line. It looks like that the native is broken of Linux Artifact version 6594.

@MauriceHandwerker 
Can you send me a link to where you saw this written down? Because I'm currently testing it in a linux docker environment and it doesn't work for me either. So it is actually bad for native.

**Comment by MauriceHandwerker** [comment]
> > Ok I temporally fixed the error.
> > es_extended/client/functions.lua : 834
> > ```lua
> > if props.driftTyresEnabled then          
> >         --SetDriftTyresEnabled(vehicle, false)
> >     end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I just commented the line. It looks like that the native is broken of Linux Artifact version 6594.
> 
> @MauriceHandwerker Can you send me a link to where you saw this written down? Because I'm currently testing it in a linux docker environment and it doesn't work for me either. So it is actually bad for native.

I didnt see it somewhere.
I just searched for it in the file and tried it. After that it worked. 
https://docs.fivem.net/natives/?_0x5AC79C98C5C17F05

**Comment by MauriceHandwerker** [comment]
Is in the first message

**Comment by TheFantomas** [comment]
> Is in the first message

Hello @MauriceHandwerker,

after a little consultation and finding out that this is FiveM's fault, we decided to completely remove props.driftTyres.

Commit Link: https://github.com/esx-framework/esx_core/commit/571888cfe042cb1966f42700c6a75b245ae1f91f

For now, you can only find this solution in the dev branch of ESX. And then when it comes out in version 1.10.2.

Best regards and have a nice day
ESX Director (Mainteniner)
Fantík
