### ISSUE TITLE
[Feature Request] - esx_core - Better setcoords command

### ISSUE THREAD

**Issue by tekkenkkk** [esx-framework/esx_core#1143]
**Describe the Feature**
Accept more values and correct them, for example I like to copy-paste my coordinates from scripts and it looks like this

```c
/setcoords 123.0, 321.0, 123.0
```

so there are commas after the coordinates, it's easy to remove them and it would help me and other users.

**Additional context**
example of comma removal (using rn)
```lua
for k,v in pairs(args) do
    local formatted = string.gsub(v, ",", "")
    args[k] = tonumber(formatted)
end
```

**Comment by Gellipapa** [comment]
Hi! Thank you for feature request. 
Is there a case where you should not delete the comma again?
Besides this, we should extend the setcoords, command with tp to have a shorter setcoords. We will think about it. Thanks.

**Comment by Gellipapa** [comment]
#1154  Implement this request.
