### ISSUE TITLE
GetExtendedPlayers refactor

### ISSUE THREAD

**Issue by Gellipapa** [esx-framework/esx_core#1151]
We need to modify the function a bit, because it is not the best to use in some cases.

Let's look at an example: 
I would like to know how many police and sheriffs there are in total.

local policesheriffCount = ESX.GetExtendedPlayers('job', {'police', 'sheriff'})
The result is: "sheriff:{}, police:{{xplayer},{xplayer}}"
Now to find out how many police and sheriffs there are in total. I have to double for loop because I get two table back.

Look something like this:
```
        local datas = ESX.GetExtendedPlayers('job', {'police', 'sheriff'})
        local count = 0
        for _,dataValue in pairs(datas) do
            for _, v in pairs(dataValue) do
                count = count + 1
            end
        end
```
A solution to this could be that if the third parameter is true, then return everything in a table or if the third parameter is 'count' then just count them or something like that.

The point is to make it as easy to use as possible and dynamic enough. 

In most cases 98% of the scripts are used for count, the rest for xPlayer. So there are not that many cases but you have to find a solution because double for loop is not a solution.

**Comment by CsokiHUN** [comment]
I think a separate function would be better, like ESX.GetNumOfPlayers({'police', 'serif'})

Anyway, good idea, just need a good implementation so that the server doesn't flame if there are too many players

**Comment by TrymTube** [comment]
if you will make that a seperate function only one will be used in the future or one gets removed ( in this case the one that does less stuff )
I find it a pretty simple solution with the table in GetExtendedPlayers

**Comment by Gellipapa** [comment]
> if you will make that a seperate function only one will be used in the future or one gets removed ( in this case the one that does less stuff ) I find it a pretty simple solution with the table in GetExtendedPlayers

Hi! Can you explain what you mean by "simple solution"?
This is currently also manage a table, not this problem.

**Comment by Kenshiin13** [comment]
> if you will make that a seperate function only one will be used in the future or one gets removed ( in this case the one that does less stuff ) I find it a pretty simple solution with the table in GetExtendedPlayers

These two functions serve distinct purposes. One function provides a complete handle to the player object, while the other function only returns the count of players that meet specific criteria. Introducing an additional function won't render the other one useless; instead, it will provide a more distinct and defined role for each.

**Comment by thelindat** [comment]
> I have to double for loop because I get two table back.

Really questioning the choices constantly being made on this project.. Either way it returns array-like tables, so you don't need any loops.

`GetNumPlayers` is a workable solution if you just want count, but you often want to trigger events on the clients that have the job (or key-value).

I also have [this gist](https://gist.github.com/thelindat/93311a4fd6ea6c1d4427438a533e228c) for handling this stuff specifically; which worked until you guys decided to drop the onDuty thing in the next release.

**Comment by Kenshiin13** [comment]
This is literally the point tho. Getting the count, not a table full of player objects you won't even work with.

**Comment by thelindat** [comment]
> This is literally the point tho. Getting the count, not a table full of player objects you won't even work with.

I'm trying to correct this misinformation that you can't get the count without iterating over the result.
```lua
local data = ESX.GetExtendedPlayers('job', {'police', 'sheriff'})
local count = #data.police + #data.sheriff
```

However in many cases you also need player ids, e.g. triggering a 911 call for a robbery.

`ESX.GetExtendedPlayer` was added to replace terrible xPlayer loops, calling `ESX.GetPlayer` on every online player.
`ESX.GetPlayers` should probably have the same filtering added, returning just the player ids.

**Comment by Kenshiin13** [comment]
You're absolutely right, that would work. There is no need for an extra loop as @Gellipapa proposed. However, I still believe that it is a good idea to separate those functions in case you really just need the count, and not the whole player objects. For example, if you have a HUD that shows how many players with certain jobs (Police/EMS etc.) are currently online.

**Comment by thelindat** [comment]
Add the filtering to `ESX.GetPlayers`, then

```lua
function ESX.GetNumPlayers(...)
    return #ESX.GetPlayers(...)
end
```

Otherwise if somebody wants to adapt the gist I linked to maintain lists of job members and GlobalStates with the job counts.

**Comment by Kenshiin13** [comment]
> Otherwise if somebody wants to adapt the gist I linked to maintain lists of job members and GlobalStates with the job counts.

That wouldn't work if no filter is provided in the GetNumPlayers() function, as it would return ESX.Players, which contains nil values. Also, why return a a huge array when you're not even going to work with it.

**Comment by Kenshiin13** [comment]
This new function doesn't break anything. It doesnt make GetExtendedPlayers() any less relevant either. It gives developers the option on whether they need entire player objects to work with, or simply the count. I don't understand the issue to be honest.

**Comment by thelindat** [comment]
> as it would return ESX.Players

_Nothing_ is supposed to return the raw ESX.Players table; that's just usual ESX team breaking compatibility for no reason. As linked in your PR https://github.com/esx-framework/esx_core/commit/5e44373d80c3eb94bad3b068788f5c742adb3e30.

> why return a a huge array when you're not even going to work with it

![image](https://github.com/esx-framework/esx_core/assets/65407488/baeca483-a789-4338-bafa-ae7dc5d94060)

> why return a a huge array when you're not even going to work with it

I didn't say you need to?

**Comment by Gellipapa** [comment]
> as it would return ESX.Players

> _Nothing_ is supposed to return the raw ESX.Players table; that's just usual ESX team breaking compatibility for no reason. As linked in your PR [5e44373](https://github.com/esx-framework/esx_core/commit/5e44373d80c3eb94bad3b068788f5c742adb3e30).
> 
Hi! Yes it's full true, this is my mistake this needs to be fixed, however I would like to have the option to know that when I enter a table that result.taxi is only the taxi xPlayers, result.police is only the police xPlayers, but we will fix this because the return ESX.Players is actually not good. Thanks for the comment.

> Your best option, by the way, is still GlobalStates. You just increase and decrease as players jobs change, just as part of xPlayer.setJob.
> 
> ```lua
> GlobalState[('%s:count'):format(lastJob.name)] -= 1
> GlobalState[('%s:count'):format(self.job.name)] += 1
> ```
I think GlobalState fails because it can be overridden and the whole logic will return false results.

In many cases, it's not just the count that matters but the actual xPlayer. See police alert, I need to know the count for a check and I need to know all the active police xPlayers to be able to send them an event. Of course you could also get for ID but for now I want to use xPlayer.triggerEvent().

**Comment by Gellipapa** [comment]
#1169 Implement GetNumPlayers method, this issue close.
