### ISSUE TITLE
[Bug] - @es_extended/server/onesync.lua

### ISSUE THREAD

**Issue by Basttv** [esx-framework/esx_core#1152]
[  script:es_extended] SCRIPT ERROR: @es_extended/server/onesync.lua:71: attempt to call a nil value (global 'CreateVehicleServerSetter')
[  script:es_extended] > [global chunk] (@es_extended/server/onesync.lua:71)
[  script:es_extended] > fn (@es_extended/server/onesync.lua:69)

Hello pk it has a bug when I do /car bf400 the spam vehicle not etc.

**Comment by MoskalykA** [comment]
What's your version of fivem?

**Comment by Basttv** [comment]
https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/6624-81fd97f8ee7def9f89fb2aafa99a13aadc045d10/fx.tar.xz

**Comment by Gellipapa** [comment]
Hi! @Basttv Please read this topic and update your artifact to 6552 or bigger. Thanks
https://github.com/citizenfx/fivem/issues/2099
