### ISSUE TITLE
[Bug] - esx_extended esx:onPlayerJoined awaiting scripts

### ISSUE THREAD

**Issue by zaze06** [esx-framework/esx_core#1172]
**Describe the bug**
When trying to join my server FiveM gets stuck on Awaiting scripts and the last thing I get in the console is
```
[  script:es_extended] event esx:onPlayerJoined was not safe for net
```
I have tried the waiting game, but not for any extended period of time

**To Reproduce**
1. make a FiveM vanilla server
2. install esx_core and dependecis
2.1. use mariadb for database
3. start server, and join
4. issue

**Expected behavior**
for the game to load and for me to be able to make my character and walk around

**Screenshots**
<details>
<summary>FiveM</summary>
<img src="https://github.com/esx-framework/esx_core/assets/54169874/24d0ccbf-6cd3-43da-b444-2b9ba309b9af">
</details>
<details>
<summary>Server Console</summary>
<img src=https://github.com/esx-framework/esx_core/assets/54169874/598826fe-f866-4707-89a0-17eae170bd9d>
</details>

**Debug Info (please complete the following information):**
 - OS: Windows(both client and server)
 -  FiveM Artifact FXServer-master SERVER v1.0.0.5848
 - ESX Version: 1.10.1

**Additional context**
my server.cfg(whitout the licenseKey)
https://gist.github.com/zaze06/33e72bbfd679845701068f0ef5f13a30

**Comment by Cyzxin** [comment]
Are you using multi character on this server?

**Comment by zaze06** [comment]
no, do I need to have it for things to work?

**Comment by zaze06** [comment]
Enabling esx_multicharacter made the Identity creation menu appear. but when I press create it empties all the entry boxes, but that I guess I should put in another issue or just google and try to find a way

**Comment by Cyzxin** [comment]
no as you can see [Here](https://github.com/esx-framework/esx_core/blob/main/%5Bcore%5D/es_extended/server/main.lua#L34) the event is registered. what i can suggest is a fresh instal may resolve your issues.

**Comment by zaze06** [comment]
Fresh reinstall of esx, database or everything?

**Comment by Gellipapa** [comment]
Hi! It looks like some scripts are missing, install the whole thing from the esx recipe via txadmin and it should work.

**Comment by Maksim221i** [comment]
how to do it can someone help

**Comment by Maksim221i** [comment]
i am not good in instukshions

**Comment by Maksim221i** [comment]
can someone maby help me tru discord
