### ISSUE TITLE
[Bug] - ESX.PlayerData.coords not returning correct coords

### ISSUE THREAD

**Issue by Thunderwolfx** [esx-framework/esx_core#1176]
**Describe the bug**
Using ESX.PlayerData.coords or xPlayer.coords returns incorrect/previous coords.

**To Reproduce**
1. Use ESX.PlayerData.coords orxPlayer.coords to print the coords
2. Compare the printed coords with the players actual coords in game

**Expected behavior**
To return the players CURRENT coords.

**Screenshots**

**Debug Info (please complete the following information):**
ESX Version: 1.10.1
Artifact Version: 6645

**Comment by Gellipapa** [comment]
@Thunderwolfx Hi! Thank you for opening an issue, we will look into it soon and if found to be incorrect we will fix it.

**Comment by Gellipapa** [comment]
#1184 Fix this issue, thank you for report this bug.
