### ISSUE TITLE
[Bug] - es_extended - players command (GetExtendedPlayers issue?)

### ISSUE THREAD

**Issue by iSentrie** [esx-framework/esx_core#1182]
**Describe the bug**
Command `players` always returns 0. Was working fine until some changes in `GetExtendedPlayers ` was made.

**To Reproduce**
1. Use command `players`
2. Always return `0`

**Expected behavior**
Return actual data not just `0`.

**Debug Info**
 - ESX Version: 1.10.1

**Comment by Kenshiin13** [comment]
A [PR ](https://github.com/esx-framework/esx_core/commit/77cbe8d38887a7ff0ecd3ecb4d79e636f9afa477)has already been merged into the dev branch to address this issue.

**Comment by Gellipapa** [comment]
@Kenshiin13 Thank you for answer. Yes next release will fix this problem.
