### ISSUE TITLE
[Bug] ESX.PlayerData.coords Problem

### ISSUE THREAD

**Issue by MaximalMax07** [esx-framework/esx_core#1192]
**Describe the bug**
So im using ``ESX.PlayerData.coords`` in my script but it always returns the same coords, it seems to be coords where you have initially logged in into the server

**To Reproduce**
Use ESX.PlayerData.coords in your own script

**Expected behavior**
Returns currenct coords
**Screenshots**

**Debug Info (please complete the following information):**
 - OS: ( Windows)
 -  FiveM Artifact: Newest
 - ESX Version: Newest

**Additional context**

**Comment by Cyzxin** [comment]
You can just use the native `GetEntityCoords()` if issues are arising with the esx player data

**Comment by MaximalMax07** [comment]
> You can just use the native `GetEntityCoords()` if issues are arising with the esx player data

How can i get the current entity of the user? because without argument it returns 0

**Comment by MaximalMax07** [comment]
> You can just use the native `GetEntityCoords()` if issues are arising with the esx player data

Thanks, that one worked!

**Comment by Gellipapa** [comment]
@MaximalMax07 Hi! Next release will working correctly ESX.PlayerData.coords.
