### ISSUE TITLE
[Bug] - es_extended - Errors using console

### ISSUE THREAD

**Issue by tugapower0** [esx-framework/esx_core#1198]
**Describe the bug**
When making some comands trough server console it trow erros, the error is relative to the log system that uses the **xPlayer.name** to log on discord the user who issue the command and since its done trough server console it does not find the xPlayer.name.

**To Reproduce**
1. Go to server console'
2. Type some commands that on log use xPlayer.name
3. Lets say setjob and setgroup commands

**Expected behavior**
Dont trow errors on console.

**Screenshots**

![imagem](https://github.com/esx-framework/esx_core/assets/9769460/1a93083e-e6df-4161-acbb-1c1e426ebef8)

**Debug Info (please complete the following information):**
 - OS: Linux
 -  FiveM Artifact : 6645
 - ESX Version: 1.10.1

**Comment by Gellipapa** [comment]
Hi! Thank you for opening an issue, we will look into it soon and if found to be incorrect we will fix it.

**Comment by Gellipapa** [comment]
I tested and works well. I think you don't updated your esx_core. Compare your server/functions.lua with github repo server/functions.lua. 

RegisterCommands handle if the player is not online, does not call the callback so there should be no such error.

![image](https://github.com/esx-framework/esx_core/assets/22717950/44d624eb-5d05-4514-944c-c12ced8f4c30)

**Comment by tugapower0** [comment]
And you have adminlog enabled ? The command it self error but does work. It error only when using in server console with the Config.AdminLogging set to true.

**Comment by tugapower0** [comment]
also relative to commands, command dv or cardel always need to pass the args, if you dont pass the args it complain

**Comment by tugapower0** [comment]
![imagem](https://github.com/esx-framework/esx_core/assets/9769460/3407d462-4550-4ac3-bf67-0a7e2b61a0a6)

If use dv or cardel witouh the radius it complain and does not delete the vehicle

**Comment by tugapower0** [comment]
Just compared both files ( **server/functions.lua** ) and they match @Gellipapa

**Comment by tugapower0** [comment]
Think you did not uinderstand the issue, the issue is not relative to players online or not, is when sending the log when the command is used trough console and **Config.AdminLogging** is set to true .

**Comment by Gellipapa** [comment]
> Think you did not understand the issue, the issue is not relative to players online or not, is when sending the log when the command is used trough console and **Config.AdminLogging** is set to true .

Hi! Yes i set Config.AdminLogging to true, but callback doesn't call if xPlayer is nil this is handle RegisterCommand. 

The dv command we fixed in dev branch, next release works perfectly, but you can test only switch dev branch in github.

**Comment by tugapower0** [comment]
So wird then, like said tracking the line it complain on my prints its all relative to the log.

Error ln 30 and 386 
```
{ name = "Player", value = xPlayer.name,       inline = true }, ```

So, something wird is going on, on a side note to confirm even more, if make the commands in game there is no error and the log ends on discord, if make in console, the command run and work, but error on that part and there is no log on discord.

Maybe can check something more? ** server/functions.lua** match with the one on github

**Comment by Gellipapa** [comment]
Strange for me because I just downloaded the latest version and the dv doesn't work so I'm on the right version, but it doesn't give me an error in the logs. It just says "[WARNING] Specified Player is not online" and that's it. So the command handles it if there is no xPlayer.

**Comment by Gellipapa** [comment]
Can you zip your esx_core folder and send me in github?

**Comment by tugapower0** [comment]
@Gellipapa that is not the issue.

![imagem](https://github.com/esx-framework/esx_core/assets/9769460/cb84ed5b-3e6b-4879-973d-b1122b07d139)

The error only happens when you issue the command to someone that is on server, because, to trigger the log it need to target someone.

**Comment by Gellipapa** [comment]
> @Gellipapa that is not the issue, if the player is not on server, get the same as you and no error.
> 
> ![imagem](https://user-images.githubusercontent.com/9769460/265278697-cb84ed5b-3e6b-4879-973d-b1122b07d139.png)
> 
> The error only happens when you issue the command to someone that is on server, because, to trigger the log it need to target someone.

I see, but it's interesting because if someone is on the server then it will be xPlayer.name so the discord log shouldn't throw an error, but I'll look at it soon.

**Comment by tugapower0** [comment]
@Gellipapa the problem is retriving the name of the person who run the command, because that person is not on the server, its doing the command on server console. Thats why it errors because there is no **xPlayer.name**  for the person who run the command.

**Comment by Gellipapa** [comment]
> @Gellipapa the problem is retriving the name of the person who run the command, because that person is not on the server, its doing the command on server console. Thats why it errors because there is no **xPlayer.name** for the person who run the command. The discord log have the person who run the command, and because its done on server console it cannot identify who is and trows the error on commands.

Ohh I see i will fix at soon. Thank you for report issue.

**Comment by Gellipapa** [comment]
@tugapower0 Hi! I fixed this issue you can tested in dev branch.

**Comment by tugapower0** [comment]
Thanks @Gellipapa
