### ISSUE TITLE
[Bug] - esx_script - Setjob command

### ISSUE THREAD

**Issue by tugapower0** [esx-framework/esx_core#1204]
since build 1.9.4 having a wird error, each time make setjob command get this on chat:

![imagem](https://github.com/esx-framework/esx_core/assets/9769460/f27708a0-722a-40d6-9176-fbb114c3dbf8)

**Comment by Gellipapa** [comment]
Hi! Latest version 1.10.1 please use latest version we don't support old version any more.

**Comment by tugapower0** [comment]
My version is 1.10.1 @Gellipapa , said this error is being since 1.9.4, did not said my version is 1.9.4

**Comment by tugapower0** [comment]
It was my bad, did not wrote down my version this time. Sorry for that
