### ISSUE TITLE
[Bug/Warning] - es_extended vehicle events throw warning

### ISSUE THREAD

**Issue by RealKnoblauchbrot** [esx-framework/esx_core#1205]
**Describe the bug**
When a player enters a vehicle it throws an error in the client console

**To Reproduce**
1. Spawn a Vehicle that is not networked.
2. Enter the vehicle.

**Expected behavior**
No warning is thrown

**Screenshots**
![grafik](https://github.com/esx-framework/esx_core/assets/60825241/0a318b76-bd31-48b4-bc9a-ae7c8b2ce995)

**Additional context**
In The GetData() function in es_extended/client/modules/actions.lua uses the VehToNet native which itself uses the NETWORK_GET_NETWORK_ID_FROM_ENTITY native.

**Idea on how to fix?**
Check if the vehicle/entity is networked. And only if it is get the netId.
Maybe like this?
```lua
local function GetData(vehicle)
    if not DoesEntityExist(vehicle) then
        return
    end
    local model = GetEntityModel(vehicle)
    local displayName = GetDisplayNameFromVehicleModel(model)
    local netId = vehicle
    if NetworkGetEntityIsNetworked(vehicle) then
        netId = VehToNet(vehicle)
    end
    return displayName, netId
end
```

**Comment by Gellipapa** [comment]
@RealKnoblauchbrot Hi! I tested your snippets works perfectly, thank you for reported problem and helped fix this bug.

**Comment by Gellipapa** [comment]
Hi! 

I fixed the issue, next release include this fix.

Thanks.
