### ISSUE TITLE
[Bug] - esx_multicharacter - MDT Tablet can be opened by other player with no police job

### ISSUE THREAD

**Issue by Gameadictive** [esx-framework/esx_core#1206]
As the title says

**Comment by Gellipapa** [comment]
@Gameadictive Hi! What does MDT have to do with esx_multicharacter? It is probably not well handled in the MDT script to be able to open the MDT.

**Comment by Gameadictive** [comment]
> @Gameadictive Hi! What does MDT have to do with esx_multicharacter? It is probably not well handled in the MDT script to be able to open the MDT.

You have Reason but TGIANN the creator of the script dont want to support it. Did u know somebody that can give support? Any discord or any guy?

**Comment by Gellipapa** [comment]
> > @Gameadictive Hi! What does MDT have to do with esx_multicharacter? It is probably not well handled in the MDT script to be able to open the MDT.
> 
> You have Reason but TGIANN the creator of the script dont want to support it. Did u know somebody that can give support? Any discord or any guy?

I can't help you with that, we are developing ESX.
