### ISSUE TITLE
[Bug] - esx_identity

### ISSUE THREAD

**Issue by XianPT** [esx-framework/esx_core#1209]
**Describe the bug**
A new character joining the server. The mouse just disappears. The players start killing each other. And you can't select the Firstname bars etc ...

**Debug Info (please complete the following information):**
 - OS: ( Windows/Linux) Windows
 -  FiveM Artifact : 6683
 - ESX Version: 1.10.1

**Comment by Gellipapa** [comment]
Hi! @XianPT Thank you for report this issue, i fixed you can see changes in this commit: https://github.com/esx-framework/esx_core/pull/1210/commits/e63c5fef00cf2db2a24347bf5a9abfd131e8318d

I merged dev branch and we will publish main at soon.
