### ISSUE TITLE
[Bug] - Vehicle Spawn - Issue

### ISSUE THREAD

**Issue by EGOistentum** [esx-framework/esx_core#1214]
**Describe the bug**
If i want to spawn an towtruck or better all utility vehicles like tractor it spawns an tanker vehicle. Spawn through /car command

**To Reproduce**
/car towtruck

**Expected behavior**
Towtruck spawn instead of tanker

**Debug Info (please complete the following information):**
 - OS: Linux
 -  FiveM Artifact latest recommended 
 - ESX Version: 1.10.1

**Comment by EGOistentum** [comment]
If i spawn in with txadmin or vMenu it works btw. Just the /car command isnt working

**Comment by Gellipapa** [comment]
@EGOistentum Hi! This bug has been fixed in the new version which will be published soon and should work fine. Thanks a lot for the bug report.

**Comment by Henne86** [comment]
june 2026 and if got the same problem^^

only vmenu gets it spawned. txadmin doesnt.

and there are a lot of vehicles, wich have problems
