### ISSUE TITLE
[Bug] - es_extended - Server commands

### ISSUE THREAD

**Issue by tugapower0** [esx-framework/esx_core#1226]
**Describe the bug**
Some commands that are to be used in-game error when doing trough server console

**To Reproduce**
1. Go to server console
2. Execute for example **info**
3. See error

**Expected behavior**
Dont error on console or add some falleback with info saying the command cannot be executed on server console.
Altough on this case we can add some check if the command **info** is been doing trough server console it prints the players on the server.

```
  local xPlayers = ESX.GetExtendedPlayers()
  print('^5'..#xPlayers..' ^2online player(s)^0') -- Get overall player count
  for _, xPlayer in pairs(xPlayers) do
    print('^1[ ^2ID : ^5'..xPlayer.source..' ^0| ^2Name : ^5'..xPlayer.getName()..' ^0 | ^2Group : ^5'..xPlayer.getGroup()..' ^0 | ^2Identifier : ^5'.. xPlayer.identifier ..'^1]^0\n') -- print players info
  end
```

**Screenshots**
![imagem](https://github.com/esx-framework/esx_core/assets/9769460/061013a7-7f7b-48d8-ae0a-9f307ce5d94c)

**Debug Info (please complete the following information):**
 - OS: Linux
 -  FiveM Artifact: 6683
 - ESX Version: 1.10.2

**Comment by Gellipapa** [comment]
@tugapower0  Hi! I don't think we need to issue a separate release for this, currently the commands that throw an error are the ones that can't be called in server console such as: job,info, bring,goto,tpm,coords.
