### ISSUE TITLE
es_extended field JobsPlayerCount error

### ISSUE THREAD

**Issue by XoHydroX** [esx-framework/esx_core#1230]
when player joins server i get this @es_extended/server/main.lua:404: attempt to index a nil value (field 'JobsPlayerCount')

**Comment by Arctos2win** [comment]
hey @XoHydroX, 

could you create a support post in our official discord 
so that we can investigate this further with you.

**Comment by Gellipapa** [comment]
Hi! @XoHydroX Do you use latest version?

**Comment by XoHydroX** [comment]
Yes I can do that when I get home and yes I use the new es_ 1.10.2

**Comment by Gellipapa** [comment]
> Yes I can do that when I get home and yes I use the new es_ 1.10.2

Hm interesting, i download latest version and deploy new server and works perfectly. I think you try update old core and you get this error.

**Comment by XoHydroX** [comment]
I made a backup of core 1.10.1 and deleted old core and put new core files in

**Comment by XoHydroX** [comment]
Made a support ticket on discord

**Comment by Gellipapa** [comment]
We've tested it several times and it works fine with no bugs. In the future if there is still an error then report back, but it shouldn't because we have tested it several times and it works.

**Comment by XoHydroX** [comment]
Well would been nice for some help on figure it out  why it works for y’all and not others

**Comment by Arctos2win** [comment]
Hey @XoHydroX, 

sorry for the late reply, can you send the post link ( discord ) 
in here please ?
