### ISSUE TITLE
[Bug] - es_extended - Metadata

### ISSUE THREAD

**Issue by tugapower0** [esx-framework/esx_core#1233]
**Describe the bug**
When the player enters the server the health and armour its not being restored.

**To Reproduce**
1. Enter the server
2. Equip a armour or loose some health
3. Exit the server
4. Enter again

**Expected behavior**
Player health and armour should be restored when it enters the server.

**Debug Info (please complete the following information):**
 - OS: Linux
 -  FiveM Artifact : 6683
 - ESX Version: 1.10.2

**Additional context**
No idea if older version the bug was already present. Also noticed on database its not saving healt or armour on users metadata table.

**Comment by Gellipapa** [comment]
Hi! @tugapower0 

I tested latest es_extended version and works perfectly. I set my hp and armor after i leave server and join and load my hp and armor. 

![image](https://github.com/esx-framework/esx_core/assets/22717950/84854fd1-0d94-42dd-ad63-659ded923b0a)

The problem is not with ESX.
