### ISSUE TITLE
esx_progress bar cancel callback doesn't seem to work

### ISSUE THREAD

**Issue by ram97prasath** [esx-framework/esx_core#1235]
**Describe the bug**
onCancel callback for the Progress bar doesn't seem to work.

**To Reproduce**
1. setup a progressBar with onCancel, (like showed in README.md)
2. exports["esx_progressbar"]:Progressbar("Making Pizza", timeToCook, {
            FreezePlayer = true,
            animation ={
                type = "anim",
                dict = "anim@mp_player_intmenu@key_fob@",
                lib ="fob_click"
            },
            onFinish = function()
                exports["esx_notify"]:Notify("info", 3000, "Cooked pizza!")
                alreadyCooking = false
                makingPizza = false
            end,
            onCancel = function ()
                exports["esx_notify"]:Notify("info", 3000, "Cooking cancelled!")
                alreadyCooking = false
                makingPizza = false
            end
        })

**Expected behavior**
When cancel key is pressed the onCancel function should be called.

**Local Fix (that I use)**
    if CurrentProgress.onCancel then CurrentProgress.onCancel() end (on line: 45 CancelProgressBar() )

**Screenshots**

**Debug Info (please complete the following information):**
 - OS: ( Windows/Linux)
 -  FiveM Artifact
 - ESX Version:

**Additional context**

**Comment by Gellipapa** [comment]
@ram97prasath Hi! I fixed this issue, thank you for report issue. Next release works perfectly progressbar onCancel callback call.
