### ISSUE TITLE
inventory won’t open esx 

### ISSUE THREAD

**Issue by bk4cs** [esx-framework/esx_core#1245]
Hi, my inventory won't open. When I click the button for the inventory, my mouse comes up and the logo for the inventory. I've been trying to fix it for hours now but getting nowhere. Anyone know what the problem could be or have the same problem? Let me know! :)

**Comment by thesysadmindev** [comment]
We will need more information than this. Are there any errors on the client or server consoles? Do you have any screenshots?

**Comment by Gellipapa** [comment]
@bk4cs Hi! Officially, esx has a context menu based inventory. So probably if you have an image/logo in yours it is not an official ESX script so contact the script creator and they can help you with that.
