### ISSUE TITLE
[Bug] - es_extended

### ISSUE THREAD

**Issue by CzlowiekNinja2021** [esx-framework/esx_core#1248]
**Describe the bug**
When we register the command and the argument type we select "merge" ESX returns a problem with argument validation
example kick 1 blah blah blah

**Comment by thesysadmindev** [comment]
@CzlowiekNinja2021 gonna need a lot more than that. Code samples, screenshots, "blah blah blah".

**Comment by Gellipapa** [comment]
@CzlowiekNinja2021 Hi! Please write down how to reproduce this issue and we will can this.

**Comment by CzlowiekNinja2021** [comment]
example command:
`ESX.RegisterCommand("kick", "support", function(xPlayer,args)

	if xPlayer.source == args.playerId.source then
		return xPlayer.showNotification("Nie możesz wyrzucić samego siebie", "error")
	end
	
	args.playerId.kick(args.reason)
	
end, true, {
	help = 'Wyrzuca gracza z serwera',
	validate = true,
	arguments = {
		{name = "playerId", help = "ID gracza którego chcesz wyrzucić z serwera", type = "player"},
		{name = "reason", help = 'Podaj powód wyrzucenia, pamiętaj aby powód podać w cudzyslowach', type = "merge"}
	}
})

dont work: 
`kick 1 reason reason`

work command, dont return validation
`kick 1 "reason reson" `
`

Sory my english bad :/

**Comment by Gellipapa** [comment]
@CzlowiekNinja2021 Hi! If you use merged type please change validate to false and works perfectly. I take picture i tested. 
![image](https://github.com/esx-framework/esx_core/assets/22717950/9f64345e-0e88-4902-837b-46cdc6d04420)
