### ISSUE TITLE
[Bug] - esx_banking - Issue

### ISSUE THREAD

**Issue by timonation** [esx-framework/esx_core#1251]
**Describe the bug**

**To Reproduce**
1. Go to 'ATM'
 Sometimes the textui doesnt dissappear and can use from any location on the map. only reconnect helps then

**Screenshots**
![image](https://github.com/esx-framework/esx_core/assets/35240334/e7a72f77-6db2-441f-8cb2-946c82c61a9c)

**Debug Info (please complete the following information):**
 - OS: Win
 -  Newest
 - ESX Version: 1.8.5

**Comment by thesysadmindev** [comment]
> * ESX Version: 1.8.5

ESX 1.8.5 is an unsupported version of the framework. Please upgrade to the latest version (being 1.10.2) and reconfirm the issue still exists.

**Comment by Gellipapa** [comment]
@timonation Hi! I tested latest version works perfectly. Please update your esx_core and retest.
