### ISSUE TITLE
[Bug] - esx_script - Issue

### ISSUE THREAD

**Issue by Sarunas2024** [esx-framework/esx_core#1260]
esx  police job is not posible take the weapon from armory
when yu put weapon in armory wont save to sql

[script:esx_datastore] SCRIPT ERROR: @esx_datastore/server/classes/datastore.lua:34: attempt to index a nil value (local 'obj')
[script:esx_datastore] > ref (@esx_datastore/server/classes/datastore.lua:34)
[script:esx_datastore] > ref (@esx_policejob/server/main.lua:234)
[script:esx_datastore] > handler (@esx_datastore/server/main.lua:66)
[script:esx_datastore] > ref (@esx_policejob/server/main.lua:233)
[script:esx_datastore] > handler (@es_extended/server/modules/callback.lua:19)

this error i am geting

**Comment by Gellipapa** [comment]
@Sarunas2024 Hi! Please update your ESX and clear database. If you use latest esx resources works perfectly policejob and other resources.
