### ISSUE TITLE
[Bug] - es_extended - Health recharging

### ISSUE THREAD

**Issue by iSentrie** [esx-framework/esx_core#1273]
Health recharge is active no matter of the settings. Disabling manually after client is loaded does actually disable recharging, however doesn't by framework.

_**No multichar resource used**_
https://github.com/esx-framework/esx_core/blob/9c84a675d5a1c4c39150a388eb908b9cf070a92a/%5Bcore%5D/es_extended/client/main.lua#L95-L97

**To Reproduce**
1. Connect to server
2. Get your health around 120 to trigger recharging
3. Health recharges

**Expected behavior**
Health should not recharge if `Config.DisableHealthRegeneration = true`

 - ESX Version: v1.10.2
- Probably same issue with #1272

**Comment by Gellipapa** [comment]
@iSentrie Hi! Yes it's bug, 5 months ago, i accepted bad PR sorry, we can fix issue at soon. BAD PR: https://github.com/esx-framework/esx_core/pull/1138

**Comment by Gellipapa** [comment]
#1277 @Thekuca Fixed this issue, you can see in dev branch we publish in main at soon.

**Comment by tiago-caldeira** [comment]
This bug is still active if anyone can check

**Comment by iSentrie** [comment]
> This bug is still active if anyone can check

it's not. update your esx.

**Comment by tiago-caldeira** [comment]
I'm using version 1.12.3 and I don't have any other script that makes this happen

**Comment by iSentrie** [comment]
> I'm using version 1.12.3 and I don't have any other script that makes this happen

Cool. Update your ESX.
