### ISSUE TITLE
[Bug] - esx_progressbar - missing onCancel() call

### ISSUE THREAD

**Issue by Ekhion76** [esx-framework/esx_core#1274]
**Describe the bug**
There is no onCancel() call in the new version.

In the event of an interruption, the onCancel call is not executed. The function is included in the documentation, but it has been removed from the script.

**Comment by Gellipapa** [comment]
Hi! @Ekhion76 Thank you for report issue, but we can fixed this, you can see fix this commit in dev branch: https://github.com/esx-framework/esx_core/commit/598c2f7c9fa34d7a6052c9bb92dfc15203622404
