### ISSUE TITLE
[Bug] Scandinavian letters in name format

### ISSUE THREAD

**Issue by MrWhiteFIN** [esx-framework/esx_core#1280]
When creating a character it doesn't allow characters Ö, Ä and Å which are used, for example, in Finnish.

**Comment by MrWhiteFIN** [comment]
> @MrWhiteFIN Hi! By default, UTF-8(Full Unicode set not supported.) is not supported by lua, so we can't do it for you.
> 
> Alternatively, we can suggest you to type this regex expression and you will be able to use it, but we can't publish it, you have to type it yourself.
> 
> Look for this code in your script and replace it with the one I sent after a script restart and it will accept the characters in your name.
> 
> https://github.com/esx-framework/esx_core/blob/main/%5Bcore%5D/esx_identity/server/main.lua#L73C23-L73C23
> 
> ```
> local function checkAlphanumeric(str)
>     return (string.match(str, "[^a-zA-ZáéíóöőúüűÁÉÍÓÖŐÚÜŰÄäÖöÅåÆæØø]"))
> end
> ```
> 
> Of course, if a character is left out, you will have to replace it yourself by entering the character fields at the end of the list above.

Hi, thanks for replying,

Unfortunately, that code didn't fix the problem. It still doesn't allow the characters. Can some else script (multichar? database?) cause this?

😀😀

**Comment by Gellipapa** [comment]
@MrWhiteFIN Hi! Any error? Server or client side?

**Comment by MrWhiteFIN** [comment]
> @MrWhiteFIN Hi! Any error? Server or client side?

No errors. It just says "Please match the requested format" below the name text block.

**Comment by Gellipapa** [comment]
> > @MrWhiteFIN Hi! Any error? Server or client side?
> 
> No errors. It just says "Please match the requested format" below the name text block.

This is interesting because it returns the result it should work on. I'll try it in a moment.

**Comment by Gellipapa** [comment]
![image](https://github.com/esx-framework/esx_core/assets/22717950/9a2e09e7-cb15-4733-a7b9-f8d139cd9da5)
Ohh this is frontend problem :)

**Comment by MrWhiteFIN** [comment]
> ![image](https://private-user-images.githubusercontent.com/22717950/297510235-9a2e09e7-cb15-4733-a7b9-f8d139cd9da5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MjM4NzMsIm5iZiI6MTcwNTUyMzU3MywicGF0aCI6Ii8yMjcxNzk1MC8yOTc1MTAyMzUtOWEyZTA5ZTctY2IxNS00NzMzLWE3YjktZjhkMTM5Y2Q5ZGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDIwMzI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMDhjMThmZTMxMzQzNDY4Y2M0YzlmMjcxMWEzZDhlYjUzNmM3ZDBiYTRjZWYwZjdmY2U5MDQ5M2RjMDZmZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t79FSV_r1kmOg8hAJET7YzoJRrKYJfWlehWdWB-iWuQ) Ohh this is frontend problem :)

What do you mean by that and how can I fix it?
