### ISSUE TITLE
[Bug] - es_extended - Check if ox_inventory is in the resources folder but not if it's started.

### ISSUE THREAD

**Issue by s1nyx** [esx-framework/esx_core#1291]
**Describe the bug**
If you have ox_inventory in your resources folder but don't want to start it for X reason (so you didn't put it in the server.cfg) you should expect es_extended to not use it right? 

**To Reproduce**
Start a blank server including the core, a db and ox_inventory.
Don't start the ox_inventory.

**Expected behavior**
It should not only check if ox_inventory is present and should also check if it's running.

**Additional context**
I am talking about this code in the file `es_extended/server/common.lua`:
```
if GetResourceState('ox_inventory') ~= 'missing' then
	Config.OxInventory = true
	Config.PlayerFunctionOverride = 'OxInventory'
	SetConvarReplicated('inventory:framework', 'esx')
	SetConvarReplicated('inventory:weight', Config.MaxWeight * 1000)
end
```

**Comment by Gellipapa** [comment]
Hi! @s1nyx I think this is doable, thanks for the issue. We will look into it and get back to you soon.

**Comment by s1nyx** [comment]
> Why should you have ox_inv on the server without starting it?

Hi, 

Because like I create scripts compatible with multiple inventories and I need to start/stop some resources on the same server.

**Comment by Gellipapa** [comment]
> > Why should you have ox_inv on the server without starting it?
> 
> Hi,
> 
> Because like I create scripts compatible with multiple inventories and I need to start/stop some resources on the same server.

It's a perfectly valid argument that it will soon be released as a PR in the dev branch, followed in a few days by the 1.10.3 release. 

Thank you for report this issue.

**Comment by Gellipapa** [comment]
https://github.com/esx-framework/esx_core/pull/1290/commits/0b01cfd287881285b2ed34845e348397defe5911
