### ISSUE TITLE
[Bug] - cron- not working 

### ISSUE THREAD

**Issue by DyroS3** [esx-framework/esx_core#1294]
**Describe the bug**
When I use cron above 1.10, I find that I can't get cron to work properly, when I use cron below 1.10, I find the code to work properly

**Screenshots**
![image](https://github.com/esx-framework/esx_core/assets/64310374/43185023-35fc-474d-9b7a-30f3feec6e91)

**Debug Info (please complete the following information):**
 - OS: Windows
 -  FiveM Artifact: 7359
 - ESX Version: 1.10.3

**Comment by Gellipapa** [comment]
Hi! @ItsKuf I remember that you did the patch on cron, can you tell me something about that? Thanks.

**Comment by tugapower0** [comment]
no idea if relative... @Gellipapa 
![imagem](https://github.com/esx-framework/esx_core/assets/9769460/80c2e27b-9b6a-4094-80b7-43ac5b37e7c3)

**Comment by Gellipapa** [comment]
@tugapower0 Hi! I think you don't pass cb parameters. Can you show me any code snippet where you use "cron:runAt" event?

**Comment by tugapower0** [comment]
Not using esx anymore @Gellipapa, sorry

**Comment by Gellipapa** [comment]
@tugapower0 Hi! It's okey, no problem, we hope to see you again.

**Comment by Kenshiin13** [comment]
Is this still relevant @Mycroft-Studios? I couldn't reproduce this.

**Comment by tugapower0** [comment]
@Gellipapa , went back to esx, using 1.10.10 right now and still got that.

The only event have on server that triggers cron is esx_society

https://github.com/esx-framework/esx_society/blob/main/server/main.lua#L428

**Comment by tugapower0** [comment]
![imagem](https://github.com/user-attachments/assets/7f488791-f096-4ccc-b4e9-388b2e35c118)

Same with ESX Legacy 1.11.1
