### ISSUE TITLE
[Bug] - es_extended - After relog, player are not recognized as dead

### ISSUE THREAD

**Issue by iSentrie** [esx-framework/esx_core#1297]
When player dies and does reconnect, he's not recognized as dead and dead player cannot call for emergency services also can't see respawn/bleedout timer.

**To Reproduce**
1. Die
2. Quit game
3. Connect back to game
4. Player won't receive option to call for emergency or see timer until respawn.

**Debug Info:**
 - OS: Linux
 - FiveM Artifact b7330
 - ESX Version: 1.10.3
 - **No multichar** ⚠️

![image](https://github.com/esx-framework/esx_core/assets/29688478/dfb977aa-402b-4ac8-b8e3-ee8d73e5217b)

**Comment by Gellipapa** [comment]
@iSentrie Hi! Thank you for report issue. Is there any modification within es_extended in your client/main.lua esx:playerLoaded event?

**Comment by iSentrie** [comment]
> @iSentrie Hi! Thank you for report issue. Is there any modification within es_extended in your client/main.lua esx:playerLoaded event?

No, 1:1, not modified, however I updated only es_extended, if any other resource could have impact to this, then it might be on my side.

**Comment by Gellipapa** [comment]
> > @iSentrie Hi! Thank you for report issue. Is there any modification within es_extended in your client/main.lua esx:playerLoaded event?
> 
> No, 1:1, not modified, however I updated only es_extended, if any other resource could have impact to this, then it might be on my side.
> 
> Like, hm, the issue is actually with esx_ambulancejob, because this script doesn't show respawn timer, so a bit tricky to choose where to look for an issue, but my guess is that metadata stuff kills player so fast, that not all data have been received at that time in other resources?

We found the problem because it doesn't use multichart, so there is no delay, and the metadata ped setup runs before the actual ped spawn, and that's the problem.

**Comment by iSentrie** [comment]
So the plan is to use "3000" delay for both, not just multichar? Like so

```lua
RegisterNetEvent("esx:playerLoaded")
AddEventHandler("esx:playerLoaded", function(xPlayer, isNew, skin)
    ESX.PlayerData = xPlayer

    if not Config.Multichar then
        exports.spawnmanager:spawnPlayer({
            x = ESX.PlayerData.coords.x,
            y = ESX.PlayerData.coords.y,
            z = ESX.PlayerData.coords.z + 0.25,
            heading = ESX.PlayerData.coords.heading,
            model = `mp_m_freemode_01`,
            skipFade = false,
        }, function()
            TriggerServerEvent("esx:onPlayerSpawn")
            TriggerEvent("esx:onPlayerSpawn")
            TriggerEvent("esx:restoreLoadout")

            if isNew then
                TriggerEvent("skinchanger:loadDefaultModel", skin.sex == 0)
            elseif skin then
                TriggerEvent("skinchanger:loadSkin", skin)
            end

            TriggerEvent("esx:loadingScreenOff")
            ShutdownLoadingScreen()
            ShutdownLoadingScreenNui()
        end)
    end

    Wait(3000)
    ESX.PlayerLoaded = true
    ```
