### ISSUE TITLE
SCRIPT ERROR: @es_extended/server/main.lua:319: attempt to index a nil value (field 'JobsPlayerCount')

### ISSUE THREAD

**Issue by XoHydroX** [esx-framework/esx_core#1324]
get this error when player leaves and joins 
[  script:es_extended] SCRIPT ERROR: @es_extended/server/main.lua:333: attempt to index a nil value (field 'JobsPlayerCount')
[  script:es_extended] > loadESXPlayer (@es_extended/server/main.lua:278)
[  script:es_extended] > handler (@es_extended/server/main.lua:33)
[  script:es_extended] > rawExecute (@oxmysql/dist/build.js:26554)
[  script:es_extended] > runMicrotasks (<anonymous>:0)
[  script:es_extended] > processTicksAndRejections (node:internal/process/task_queues:96)

anyway i can just remove this

**Comment by Gellipapa** [comment]
@XoHydroX Hi! Do you use latest es_extended version?

**Comment by Gellipapa** [comment]
@XoHydroX Interesting, i builded new server and works very good. Do you added any value in jobs table in db?

**Comment by XoHydroX** [comment]
I’ll have to check when I get off work

**Comment by Gellipapa** [comment]
> I’ll have to check when I get off work What’s the db so post to look like for the table

You can see correct sql in esx_core, [SQL] folder.

**Comment by Gellipapa** [comment]
@XoHydroX Hi! Have you managed to fix it? Can I close the issue?

**Comment by XoHydroX** [comment]
Yea it was my doing
