### ISSUE TITLE
[Feature Request] - es_extended - Old default inventory back

### ISSUE THREAD

**Issue by granfuego** [esx-framework/esx_core#1325]
So, now the inventory works with esx_context, but is there a way to add a option in config that you can choose between esx.ui.menu and esx_context. Because the old inventory was good because it could be used by arrow keys. Esx_context works with mouse and so does other inventories what i have found on the internet (huds) 
And yeah, i could go back to old versions of es_extended, but i want to use the newest version.

If you could tell me a way to go back with esx ui menu, sure tell me please.

But this feature in my opinion is great, if people would still like to use latest version of es_extended and still use old style default inventory!
(found this picture from google, its like that, but its redesigned esx_menu_default)
![image](https://github.com/esx-framework/esx_core/assets/74319971/64b001ab-6b32-480f-9d9d-3607d518458c)

**Comment by Gellipapa** [comment]
@granfuego Hi! I will ask the team how appropriate it would be to do this. If it comes back it will be switched on/off based on a config.

**Comment by granfuego** [comment]
> @granfuego Hi! I will ask the team how appropriate it would be to do this. If it comes back it will be switched on/off based on a config.

Okay, and then there would be a problem with other scripts aswell because other scripts now uses context.
Also, is there a way to use context with arrow keys and not with my mouse? that would basically fix the problem.

Example:
If i would be a cop and needed to go after someone, the context menu with f6 in policejob isnt great. you cant move while using it, so no handcuffing anyone because of course they can run away.
Also, finnish servers usually are more kind of shooting and criminal activity, so we need a inventory that we can use while being in a shooting scenario (bulletproof vests, heals) But i still want to make my server with the latest esx, and not old versions.

**Comment by Gellipapa** [comment]
@granfuego 

> > @granfuego Hi! I will ask the team how appropriate it would be to do this. If it comes back it will be switched on/off based on a config.
> 
> Okay, and then there would be a problem with other scripts aswell because other scripts now uses context. Also, is there a way to use context with arrow keys and not with my mouse? that would basically fix the problem.
> 
> Example: If i would be a cop and needed to go after someone, the context menu with f6 in policejob isnt great. you cant move while using it, so no handcuffing anyone because of course they can run away. Also, finnish servers usually are more kind of shooting and criminal activity, so we need a inventory that we can use while being in a shooting scenario (bulletproof vests, heals) But i still want to make my server with the latest esx, and not old versions.
> 
> and, sorry if my explanation is complicated, english isnt my main language:)

Yes, this is exactly the question whether it should be solved globally or locally, i.e. that a given script uses context and a given script does not use context. 

This is the questionable part. 

Yes we know that context is an obsolete thing, it was a very old rudimentary context menu experiment, but for some reason everything was rewritten for it. 

We also know that context is about useless in the future we will work on it to have a usable context menu for ESX.

I'll see how complicated it would be to write a wrapper for it and report back with the results.

**Comment by granfuego** [comment]
@Gellipapa hey, just wondering how long would it take to add this feature? No rush of course but i just looked and its in pending so i just thought id ask, because i would like to add it on my server as soon as the update comes for es_extended

**Comment by granfuego** [comment]
@Gellipapa okay, i can try my best to make it myself and if the context menu will support keyboard inputs then thats just fine. Because then its almost as same as the old one. 
But no worries, i almost forgot about this because i have been busy with my server, and i know you are busy too to answer every message.

But glad to hear the support for esx context is coming!

**Comment by Gellipapa** [comment]
@granfuego Hi! Since it will take more time to rewrite the context menu, I have written the old logic for you, so copy the file in this zip in the client/modules folder and replace the fxmanifest file with the one in the .zip file. After that a server restart and then you can use it smoothly by pressing F2 the old esx_menu_default inventory will appear.

[default_inventory.zip](https://github.com/esx-framework/esx_core/files/14577337/default_inventory.zip)

**Comment by granfuego** [comment]
@Gellipapa Thanks for making it!! I just got off my pc but seems like i gotta go back on it and test it out.😅

**Comment by granfuego** [comment]
@Gellipapa Im not sure what i did wrong but didnt work, here is what i did.
1. I put the default_inventory.lua in es_extended/client/modules
2. I replaced the fxmanifest.lua
3. restarted my server
4. tried it but didnt work
5. Then tried to change Config.EnableDefaultInventory to false and true

**Comment by Gellipapa** [comment]
@granfuego Hi! Ohh sorry i uploaded bad zip file. I will upload new zip.

**Comment by Gellipapa** [comment]
This is fixed version.

[default_inventory-fixed.zip](https://github.com/esx-framework/esx_core/files/14594190/default_inventory-fixed.zip)

**Comment by Gellipapa** [comment]
I am glad that it worked.

**Comment by Pascu4l** [comment]
Hello, I have tried doing the same thing and it doesn't work, could you help me?

**Comment by east-22** [comment]
> Hello, I have tried doing the same thing and it doesn't work, could you help me?

yeah sure add me on dc: east_22

**Comment by JotaX3x** [comment]
@Gellipapa 
Thank you very much, you helped me with a problem that was driving me crazy.

@east-22 and to you for asking ♥
