### ISSUE TITLE
[Bug] - esx_addonaccount - Issue = [script:esx_addonacco] SCRIPT ERROR: @esx_addonaccount/server/main.lua:5: attempt to index a nil value (global 'MySQL')

### ISSUE THREAD

**Issue by n0tKp888** [esx-framework/esx_core#1337]
Does anyone know how to fix this?

**Comment by Gellipapa** [comment]
@n0tKp888 Hi! You need to run ox_mysql before es_extended, you probably don't have oxmysql running, or you start it later, or it's just misconfigured. This is not an ESX problem, you have the wrong ox_mysql configuration.
