### ISSUE TITLE
Website/documentation - account suspended

### ISSUE THREAD

**Issue by iSentrie** [esx-framework/esx_core#1341]
Hi, so https://documentation.esx-framework.org account was suspended, any plans to restore it?
Discord is pretty much locked too, cannot create any new topics.
What's going on?
![image](https://github.com/esx-framework/esx_core/assets/29688478/4126f38f-860c-4338-9c69-08a7fbaad888)

**Comment by Thekuca** [comment]
There is an issue with the hosting. It will be fixed soon.
