### ISSUE TITLE
[Bug] - es_extended 

### ISSUE THREAD

**Issue by Shafat21** [esx-framework/esx_core#1347]
**Describe the bug**
Getting this error when I want to spawn a car in the world

**To Reproduce**
SCRIPT ERROR: @es_extended/server/onesync.lua:55: attempt to perform arithmetic on a nil value (local 'playerCoords')

**Expected behavior**
It should spawn me a car without an error

**Screenshots**
![image](https://github.com/esx-framework/esx_core/assets/61838416/e5e5e713-6e39-41a1-87fa-ad5d1dc72ea4)

**Debug Info (please complete the following information):**
 - OS: ( Windows)
 -  Latest
 - ESX Version: 1.10.5

**Comment by Gellipapa** [comment]
@Shafat21 Hi! This is unique case probably the coordinate you entered is nil and that's why you get error. 

Contact me on discord and I'll help you guys fix your scripted problem, but it's not a global problem, it's a local problem.
