### ISSUE TITLE
[Bug] - Ox Inventory does not work with 1.10.5

### ISSUE THREAD

**Issue by SKULL1985** [esx-framework/esx_core#1349]
Seems the new ESX 1.10.5 does not work with ox inventory no more, 
![image](https://github.com/esx-framework/esx_core/assets/42191601/930b2fa0-f83d-4a12-9886-e04e9aa992a4)

After looking at the old ESX and new there is no code in 1.10.5 for ox inventory , like the old ones

**Comment by Arctos2win** [comment]
> Seems the new ESX 1.10.5 does not work with ox inventory no more, ![image](https://private-user-images.githubusercontent.com/42191601/326291815-930b2fa0-f83d-4a12-9886-e04e9aa992a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMzY3MjUsIm5iZiI6MTcxNDMzNjQyNSwicGF0aCI6Ii80MjE5MTYwMS8zMjYyOTE4MTUtOTMwYjJmYTAtZjgzZC00YTEyLTk4ODYtZTA0ZTlhYTk5MmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDIwMzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlOGQzZTcxZTE5MTQzODM3Y2YwZjNjOWFhMTVmNGYzNDYxMjczNDVhOGNlNmYwNDNiN2VmNzQzODBiMTE2YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2TgukG0UZf7TIpGefV_sOblUHu-we_0-RhR7t-JSuQo)
> 
> After looking at the old ESX and new there is no code in 1.10.5 for ox inventory , like the old ones

Hi can you please create a thread in our discord and tag me please.

**Comment by Gellipapa** [comment]
@Arctos2win Hi! Any status?

**Comment by ExoCinki** [comment]
@Gellipapa ox_inventory (latest version) work well I'm used Esx 1.10.5

**Comment by Arctos2win** [comment]
> @Gellipapa @Arctos2win  ox_inventory (latest version) work well I'm used Esx 1.10.5

Yes we know, he updated esx from an older version but didnt add the changes inside the config we added one named Config.OxInventory. 

Thanks for letting us know 🙂
