### ISSUE TITLE
[Bug] - Multicharacter Char freeze/stuck after Char Creation

### ISSUE THREAD

**Issue by drlukask2018** [esx-framework/esx_core#1353]
**Im using a Char-Creator from VisualCore (ive tried with 2 others aswell) and everytime I finish creating my Char I spawn and my Character ist stuck/frozen**

I get no Errors in F8 or Console. and im using the latest ESX Legacy

I hope you can help me my head is already burning trying to fix this :D

**Comment by Gellipapa** [comment]
@drlukask2018 Hi! We can't help you with this, write to the discord and the community will help you, it's not a bug in ESX Legacy, it's probably a unique problem. Thanks
