### ISSUE TITLE
[Bug] - es_extended - script

### ISSUE THREAD

**Issue by K1KO11** [esx-framework/esx_core#1360]
**Describe the bug**
basically I wanted to change es_extended version 1.8.5 to 1.10.5 I changed everything and converted the scripts to "ESX = exports["es_extended"]:getSharedObject()" after that some errors appear and an infinite screen "waiting scripts". the server was working normal before i change the version

**Screenshots**
![imagem](https://github.com/esx-framework/esx_core/assets/121776043/bdbe9187-8823-4302-97c6-460a3567bb60)
![imagem](https://github.com/esx-framework/esx_core/assets/121776043/700c0279-b6d1-4d6c-8bec-64f47c8d06df)
![imagem](https://github.com/esx-framework/esx_core/assets/121776043/71dbc25d-dc9b-4d8b-80ad-789a30dac95e)
![imagem](https://github.com/esx-framework/esx_core/assets/121776043/0a2d51c5-80bf-4424-858c-c48f0b42a181)
![imagem](https://github.com/esx-framework/esx_core/assets/121776043/d9296f1a-efb2-4ffe-8a0b-9cd54943ff3c)

**Debug Info (please complete the following information):**
 - OS: ( Windows/Linux): windows
 -  FiveM Artifact: 8552
 - ESX Version:1.10.5

**Comment by K1KO11** [comment]
![imagem](https://github.com/esx-framework/esx_core/assets/121776043/b9d9afd5-3174-487e-ab9a-66bae13b1de8)
**I also have this error but I don't think it's relevant**

**Comment by Gellipapa** [comment]
@K1KO11 Hi! Thanks for write, you should read a documentation, https://documentation.esx-framework.org/tutorials/tutorials-esx/sharedevent this is your problem, we removed old ESX method and you should use export or better the use shared import.
