### ISSUE TITLE
[Bug] - es_extended\fxmanifest.lua in line 46

### ISSUE THREAD

**Issue by Who-is-Cola** [esx-framework/esx_core#1369]
**Describe the bug**
Error of double 'common/functions.lua', in the es_extended\fxmanifest.lua in line 46

**Screenshots**
![image](https://github.com/esx-framework/esx_core/assets/79643020/fe2bce25-355d-4489-80ad-b3387de493e2)

**Debug Info**
 - OS: Windows
 -  FiveM Artifact 8552
 - ESX Version: 1.10.6

**Comment by Gellipapa** [comment]
@Who-is-Cola Hi! Thanks nice catch. There was a revert and that's probably why it was left in, we'll fix it in the next release, for now it shouldn't be a problem, it will work anyway.
