### ISSUE TITLE
[Bug] -  @es_extended/server/main get error msg

### ISSUE THREAD

**Issue by Who-is-Cola** [esx-framework/esx_core#1370]
**Describe the bug**
error in the @es_extended/server/main.lua:591

**Expected behavior**
After using the 1.10.6 esx version get the error below

[  script:es_extended] SCRIPT ERROR: @es_extended/server/main.lua:591: attempt to index a nil value (local 'xPlayer')
[  script:es_extended] > ? (@es_extended/server/main.lua:591)
[  script:es_extended] > handler (@es_extended/server/modules/callback.lua:19)

**Screenshots**
![image](https://github.com/esx-framework/esx_core/assets/79643020/718654d7-3dc2-46d1-9132-b2bbe46a1938)
**Debug Info (please complete the following information):**
 - OS: Windows
 - FiveM Artifact 8552
 -  ESX Version: 1.10.6

**Comment by Who-is-Cola** [comment]
Also want to ask that if i want to add the zh-tw locales for the next version of esx. do i have to use the pull requests for github？ I look forward to your response.Many thx

**Comment by Gellipapa** [comment]
@Who-is-Cola Hi! Yes, you can use pull request and you can add some locales in core.

**Comment by Gellipapa** [comment]
@Who-is-Cola When do you get this error because if you use the latest version it works perfectly fine, loads the character etc, I just tested it.

**Comment by Who-is-Cola** [comment]
@Gellipapa oic, I encountered an error after using the new version of ESX. Tomorrow, I plan to try deleting my character in SQL and creating it again to see if the issue persists. I'll let you know the outcome after I test it.

Is there any way to add some locales in the core, apart from submitting a pull request?

Thank you for your response above.

**Comment by Gellipapa** [comment]
@Who-is-Cola Hi! Can you test please es-extended 1.10.5 version?

**Comment by Who-is-Cola** [comment]
Okay, I'll give you the answer tomorrow～

**Comment by Who-is-Cola** [comment]
Hello, i have just test the 1.10.5 and it work perfectly, and no error msg for loacal xplayer
![image](https://github.com/esx-framework/esx_core/assets/79643020/6a6728cc-e8bc-47a6-8f33-3e6e73dc55f6)

**Comment by Gellipapa** [comment]
@Who-is-Cola Hi! Please update latest version and re-test, we have released 1.10.7 hotfix soon.

**Comment by Gellipapa** [comment]
I tested works, i think this is local problems.
