### ISSUE TITLE
bug(es_extended): error's out on playerCoords

### ISSUE THREAD

**Issue by iSentrie** [esx-framework/esx_core#1371]
1️⃣ ISSUE
---
After last update, client errors out 
![image](https://github.com/esx-framework/esx_core/assets/29688478/42a5dce5-f71e-4e42-88f6-1f07e5b8795c)

https://github.com/esx-framework/esx_core/blob/0bc232185aa05462d161638551f6bc7dbb7d7894/%5Bcore%5D/es_extended/client/main.lua#L484

Edit: looks like `playerCoords` is vec3 and `coords.pickup` is vec4

2️⃣ ISSUE
---
Also after last update, it's hard to pickup items, message pops up in server console:
`[WARNING] Player Detected Cheating (Out of range pickup)`
I think since there was some changes with coords, heading is being saved too and it's getting calculated towards coordinates.

---

⚠️ _Using default inventory (no ox_inventory)_

## EDIT: pushed 2 updates for these issues.

**Comment by Gellipapa** [comment]
@iSentrie Hi! I've included the addition of heading to getCoords and it looks like it breaks all the code, so we'll get that back fixed tomorrow and eliminate all these errors. Thanks for your patience and thanks for opening the issue.
