### ISSUE TITLE
[Bug] - esx_script - Tried to spawn vehicle on the client but the position is too far away (Out of onesync range).

### ISSUE THREAD

**Issue by Harry755** [esx-framework/esx_core#1380]
**Describe the bug**
error is shown Tried to spawn vehicle on the client but the position is too far away (Out of onesync range).
even though i am near i cant spawn the vehicle from client side

**Screenshots**

 - ESX Version: 1.10.7

**Additional context**
![Screenshot 2024-07-10 001520](https://github.com/esx-framework/esx_core/assets/106462812/1c22310a-2139-40cd-8099-5aa5b84d2c62)

**Comment by MohamexDR** [comment]
you need to set the spawnpoints near you, not far away
