### ISSUE TITLE
[Bug] - esx_core - ESX.PlayerData.name retunr nill

### ISSUE THREAD

**Issue by DyroS3** [esx-framework/esx_core#1386]
**Describe the bug**
When trying to use ESX.PlayerData.name, the return value is nil

**To Reproduce**
```lua
RegisterCommand('ESX.PlayerData.name', function(source, args, raw)
  local ESX = exports['es_extended']:getSharedObject()

  print('ESX.PlayerData', ESX.DumpTable(ESX.PlayerData))
  print('ESX.PlayerData.name', ESX.PlayerData.name) -- retrun nil
end, false)
```

**Screenshots**
![image](https://github.com/user-attachments/assets/5edb2dc5-1e1d-4063-9193-9d7fcaa6e7fc)

**Debug Info (please complete the following information):**
 - OS: Windows
 - FiveM Artifact: 9214
 - ESX Version: 1.10.7

**Additional context**
When I look at the values printed by ESX.DumpTable(ESX.PlayerData), I see that there is no name header, and when I look at the kernel I see that `server` - `main.lua` finds that `userData` does not have a value for `name`. Is ESX.PlayerData.name being dropped?
![image](https://github.com/user-attachments/assets/e75710ae-6077-496e-a5bf-94573ed8fb3d)

**Comment by Gellipapa** [comment]
@DyroS3 Hi! Thanks for report problem. I corrected it, the error was that there was a refactor and the name value was not entered and therefore the player data was not received.
