### ISSUE TITLE
qb-policejob bug

### ISSUE THREAD

**Issue by osdaohdph** [esx-framework/esx_core#1390]
![螢幕擷取畫面 2024-08-15 175905](https://github.com/user-attachments/assets/76caf090-175c-438b-b994-afbadc32a9ad)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Debug Info (please complete the following information):**
 - OS: ( Windows/Linux)
 -  FiveM Artifact
 - ESX Version:

**Additional context**

**Comment by Arctos2win** [comment]
Hi @osdaohdph, 

I think its very logical that a policejob made for qbcore is 
not compatible with esx ....

If u are using esx then use the policejob from esx ... 
https://github.com/arctos2win/esx_policejob 

Greetings 
- @Arctos2win
