### ISSUE TITLE
[Bug] - Dispatch

### ISSUE THREAD

**Issue by Jason8831** [esx-framework/esx_core#1392]
deactivate vehicle dispatch audio because the function has to be modified and with version es_extended 1.10.7 you can still hear the basic vehicle dispatch sounds

**Comment by Gellipapa** [comment]
@Jason8831 Hi! Sorry i don't understand what a main problem? Can you show me any video how to reproduce this bug? Thanks.

**Comment by Jason8831** [comment]
Hello, I'm talking about Config.DisableDispatchServices = false which had the ability to remove the police scanner flag in your version 1.10.6 and when you updated to 1.10.7 this feature has disappeared. The code still removes the service vehicles but no longer disables the audio, so I did some research and it separates the system from the audio flag. 

Disable Dispatch Services 
https://docs.fivem.net/natives/?_0xDC0F817884CDD856

Disable Audio Dispatch Service  
https://docs.fivem.net/natives/?_0xB9EFD5C25018725A

**Comment by Gellipapa** [comment]
Hi! @Jason8831  We never used this native so before and after 1.10.6 we didn't use it but now I've included it so now it will disable police sounds. Next release you can test it.
