### ISSUE TITLE
[Bug] - esx_script - Can't move after selecting character

### ISSUE THREAD

**Issue by Inferno265** [esx-framework/esx_core#1394]
I can't move after i am selecting my character.

I wanted to install ox_inventory with esx_core and i got into this issue

-OS: Linux
- I am using ZAPHosting: FiveM Mod
- ESX version: 1.10.7

I was following a tutorial on youtube btw

Screenshot: 
![image](https://github.com/user-attachments/assets/fe969e3a-0dc4-4a97-a92e-a6ecdd1b6675)

**Comment by Gellipapa** [comment]
Hi! @Inferno265 We're sorry but this is an isolated case, currently 1.10.7 works fine, you probably did something wrong during installation. We recommend a clean install which is available in txadmin.
