### ISSUE TITLE
[Feature Request] - esx_script - Add better configuration

### ISSUE THREAD

**Issue by MrKill50** [esx-framework/esx_core#1401]
**Describe the Feature**
Double job or faction

**Comment by Gellipapa** [comment]
@MrKill50 Hi! Be more specific about the feature request because I don't understand what you mean, or i will close this issue.

**Comment by MrKill50** [comment]
be able to say in the es extended config if you want the possibility of having 2 jobs in games like tobacco and gang for the rp servers

**Comment by Mesrine67** [comment]
if you just want to have 2 jobs, you just need to create a system for storing several jobs 
plus gang interaction (illegal activity would be completely different) useless pay, useless clothes

**Comment by Gellipapa** [comment]
@MrKill50 Hi! It's clear what you want, but the whole core would have to be rewritten in a fundamentally different way to support the multi-group option, so this will not be implemented in legacy, we plan to implement it in infinity.
