### ISSUE TITLE
[Feature Request] - es_extended and lib - UI Overhaul and Centralization of ESX on Overextended

### ISSUE THREAD

**Issue by Mesrine67** [esx-framework/esx_core#1402]
I propose centralizing ESX around the **Overextended** library for several reasons:

1. **Resource Reduction**: By centralizing ESX on Overextended, we could eliminate 8 different resources (cron, esx_context, esx_menu_default, esx_menu_dialog, esx_menu_list, esx_notify, esx_progressbar, esx_textui) and replace them with a single resource, **ox_lib**.

2. **Optimization**: This consolidation could also bring slight optimizations by reducing scattered code and simplifying the management of the user interface.

3. **Community Adoption**: The majority of the FiveM community already uses the Overextended library. In fact, ESX already requires the use of **ox_inventory** for **esx_property** and offers it as an option in **es_extended** for better immersion. Centralizing the ESX UI around this library seems like a logical step.

4. **Removal of Additional Resources**: By using **ox_inventory**, we could also remove **esx_addonaccount**, **esx_addoninventory**, and **esx_datastore**. The features of these three resources, which have no direct equivalent in **ox_inventory**, could be integrated directly into the **es_extended** framework, further reducing the number of resources to manage (3 fewer resources for 1 additional resource).

5. **Centralization of Additional Modules**: We could also centralize **esx_license**, **esx_status**, **esx_basicneeds**, and **esx_optionalneeds** directly within **es_extended**, reducing fragmentation and improving framework cohesion.

6. **Hook System**: Adding a hook system similar to **ox_inventory** would improve ESX’s modularity and flexibility, offering developers more control over interactions with different modules.

This suggestion would allow ESX to adopt a more modern, optimized, and coherent approach in line with current community practices, while reducing complexity and the number of necessary resources.

**Comment by Gellipapa** [comment]
@Mesrine67 Hi! Thank you for this detailed description, but we have no plans to modify the legacy, we are working on the new system which will be infinity. There we are already planning to introduce ox_lib as an optionally connectable third-party resource BUT it is important to emphasize that we are also aiming to be a completely standalone system. Thank you for your understanding. Time has passed over legacy and we would like to keep it as it was and only fix bugs in it later and archive the project.
