### ISSUE TITLE
[Bug] - es_extended coords (position)

### ISSUE THREAD

**Issue by kFxDaKing** [esx-framework/esx_core#1421]
**Describe the bug**
Some players had issues with connecting to the server, they got error unknown pool pool full size == 256 while spawning.

I found it helped when i changed their coords and when i checked their coords i found this:
`{"y":-27648.0,"x":-1054.3780517578126,"heading":0.0,"z":4.864501953125}`

**To Reproduce**
Cant reporoduce, its happening just sometimes and for some players.

**Debug Info (please complete the following information):**
 - OS: Linux
 -  FiveM Artifact: b10309
 - ESX Version: version '1.10.7'

**Comment by Gellipapa** [comment]
@kFxDaKing Hi! The error you get means that for some reason the pool size memory is full, it's not a coordinate. It could be a bad script a bad mapping etc. 

What do you want to do with the coordinate?

**Comment by kFxDaKing** [comment]
> @kFxDaKing Hi! The error you get means that for some reason the pool size memory is full, it's not a coordinate. It could be a bad script a bad mapping etc.
> 
> What do you want to do with the coordinate?

Check y of the coords, that why he gets the error.
When i changed his coords, he can play again without problems.

**Comment by kFxDaKing** [comment]
They dont crash midgame with this error, but when they are connecting and spawning, we have around 100+ online palyers every day and it happend like 3 times this week, with same problem , always bad coords in position table.

Previous esx version way okay.

` function self.setCoords(coordinates)
        local ped <const> = _GetPlayerPed(self.source)
        local vector = type(coordinates) == "vector4" and coordinates or type(coordinates) == "vector3" and vector4(coordinates, 0.0) or vec(coordinates.x, coordinates.y, coordinates.z, coordinates.heading or 0.0)
        _SetEntityCoords(ped, vector.xyz, false, false, false, false)
        _SetEntityHeading(ped, vector.w)
    end`

**Comment by kFxDaKing** [comment]
![image](https://github.com/user-attachments/assets/f0586ce2-c188-4928-b17e-87067745f15d)

**Comment by Gellipapa** [comment]
@kFxDaKing Do you use multicharacter? by the way we latest version is 1.10.9.

**Comment by kFxDaKing** [comment]
> @kFxDaKing Do you use multicharacter? by the way we latest version is 1.10.9.

yes i do

**Comment by kFxDaKing** [comment]
another guy with that problem
![image](https://github.com/user-attachments/assets/ba6ae6ea-7a03-40d8-a9a4-6d79f812eeb9)

**Comment by Naifen-Phoxidas** [comment]
Had same error, but got fixed

**Comment by kFxDaKing** [comment]
> Had same error, but got fixed

how?

**Comment by kFxDaKing** [comment]
This started happening since the heading was added i think

**Comment by kFxDaKing** [comment]
It seems its happening, when they log of when falling throught map.

**Comment by Mycroft-Studios** [comment]
> This started happening since the heading was added i think

Heading has been there for years.

**Comment by kFxDaKing** [comment]
`    ---@param vector boolean
    ---@return vector3 | table
    function self.getCoords(vector)
        local ped <const> = _GetPlayerPed(self.source)
        local coordinates <const> = _GetEntityCoords(ped)

        return vector and coordinates or { x = coordinates.x, y = coordinates.y, z = coordinates.z }
    end`
    
    Version 1.10.5, we had no issues on this version

**Comment by Mycroft-Studios** [comment]
> Inside client main lua: line 35 you have to much parameters

This is not related to the issue, and is fixed in dev branch :)

**Comment by kFxDaKing** [comment]
Still happening

**Comment by Mycroft-Studios** [comment]
> Still happening 


Which ESX Version

**Comment by 7Raini** [comment]
I have the same problem

**Comment by bryansanchez379-ui** [comment]
For anyone still subscribed here: I think I found the root cause, written up in #1897.

Short version — `xPlayer.getCoords()` does no validation, and `GetPlayerPed()` returns `0` once the ped is gone, at which point `GetEntityCoords(0)` returns garbage. The saves fired by `playerDropped`, `txAdmin:events:scheduledRestart` and `serverShuttingDown` all run exactly during ped teardown, which is why it only ever hits some players and never reproduces on demand. The code path is unchanged on `main` today.
