### ISSUE TITLE
[BUG] New update error

### ISSUE THREAD

**Issue by pepi2003** [esx-framework/esx_core#1442]
Hello, when i updated to the new es_extended i get this error
![image](https://github.com/user-attachments/assets/da40b769-8479-4762-a084-23d9cb0017d6)
What could be the cause ? Could it be a bug from the update because before i didnt have this issue, just happened after the update

[  script:es_extended] SCRIPT ERROR: @es_extended/server/common.lua:44: attempt to call a nil value (field 'RefreshJobs')

**Comment by Mycroft-Studios** [comment]
Make sure you have fully updated es_extended

**Comment by pepi2003** [comment]
> Make sure you have fully updated es_extended

Would you elaborate ? I downloaded all the stuff from the [core] folder. It should be fully updated

**Comment by Mycroft-Studios** [comment]
do u see `ESX.RefreshJobs` in `es_extended/server/functions.lua`

**Comment by Mycroft-Studios** [comment]
Oh wait. Did you... try restarting es_extended?

**Comment by Mycroft-Studios** [comment]
if so, Dont ever do that, the core is not to be restarted at runtime, restart the server for that

**Comment by pepi2003** [comment]
i restarted the server i guess it works now but when i try to join the serv i get this error ? this didnt happen before the update
![image](https://github.com/user-attachments/assets/65507dfc-36d3-404f-a84c-f9f0a53ee1eb)

**Comment by Mycroft-Studios** [comment]
Are you using Multicharacter?

**Comment by pepi2003** [comment]
Nope. I dont

**Comment by Mycroft-Studios** [comment]
maybe try restarting your game, FiveM is saying you dont have a license identifier

**Comment by pepi2003** [comment]
I just inserted my old es extended and i can join normally in the  server. Are u sure the new es extended is tested or is it just me getting this error when i try to join with the updated extended ?

**Comment by pepi2003** [comment]
i downloaded a fresh copy of es extended again same error , are there anny resources that could be interfearing with it ?

**Comment by Mycroft-Studios** [comment]
I can assure you its tested, and i can assure you, that error has absoutely nothing todo with the update.
FiveM itself is telling ESX that you do not have a license identifier.
there is not much ESX can do about that, other than drop you, or spit out 40 errors while trying to create a character for a player that doesnt exist

**Comment by Mycroft-Studios** [comment]
Okay so, ive found the issue.
And its a very weird one, and the code has been like this for around a year now, so not sure why it chose now to break
