### ISSUE TITLE
[Bug] - es_extended v1.11.2 - Can't get ESX.PlayerData correctly

### ISSUE THREAD

**Issue by DyroS3** [esx-framework/esx_core#1454]
**Describe the bug**
When I have the `esx:playerLoaded` event in the latest ESX version, I find that it doesn't get the `ESX.PlayerData` correctly.

**To Reproduce**
1. Client codes:
```lua
RegisterNetEvent('esx:playerLoaded')
AddEventHandler('esx:playerLoaded', function(xPlayer)
  -- Wait(1) -- When I add wait, the following code works fine, but when I remove wait, the following code does not work.
  print('playerdata', ESX.DumpTable(ESX.PlayerData)) -- when add `Wait` it works, but when remove `Wait` it doesn't work.
end)
```
2. When I add `Wait(1)`, print data correctly
3. When I remover `Wait(1)` , print `{}`

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/5c759cfb-801a-4e13-a66f-e31aa7bc314e).
![image](https://github.com/user-attachments/assets/28a6bb6a-ed27-4a31-86c7-5aa7f894536f)

**Debug Info (please complete the following information):**
 - OS: Windows
 -  FiveM Artifact: 10822
 - ESX Version:1.11.2

**Comment by Arctos2win** [comment]
Hi @DyroS3, 

Where did you put this code ?

**Comment by DyroS3** [comment]
![image](https://github.com/user-attachments/assets/2e8d330f-8bf9-4c84-bbc8-abb38b758e80)
client codes

**Comment by Arctos2win** [comment]
> ![image](https://private-user-images.githubusercontent.com/64310374/385247075-2e8d330f-8bf9-4c84-bbc8-abb38b758e80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDc5ODksIm5iZiI6MTczMTQwNzY4OSwicGF0aCI6Ii82NDMxMDM3NC8zODUyNDcwNzUtMmU4ZDMzMGYtOGJmOS00Yzg0LWJiYzgtYWJiMzhiNzU4ZTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDEwMzQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNWQwZGI1Yzk5NGUyNTg4ZDlkNzNmNGZmODgxNDc0YTI0ZGUxZDlkZDAwZTkzMjZmOWExM2VkYWJiOTEyYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9cnF1FiGYazvu7xwJ8dwrUDoOjGdBiuDcH38e9CcOw4) client codes

this is bcs the ESX.PlayerData gets set with that event as well in the imports file

**Comment by Mycroft-Studios** [comment]
the argument xPlayer *is* ESX.PlayerData.
ESX.PlaerData itself is not set until after that event

**Comment by Mycroft-Studios** [comment]
No.
```lua
RegisterNetEvent('esx:playerLoaded')
AddEventHandler('esx:playerLoaded', function(xPlayer)
ESX.PlayerData = xPlayer
end)
```
the parameter xPlayer in the Event, **is** ESX.PlayerData

**Comment by DyroS3** [comment]
> No.
> 
> ```lua
> RegisterNetEvent('esx:playerLoaded')
> AddEventHandler('esx:playerLoaded', function(xPlayer)
> ESX.PlayerData = xPlayer
> end)
> ```
> 
> the parameter xPlayer in the Event, **is** ESX.PlayerData

Yes, I know that this parameter represents ESX.PlayerData, but isn't it true that the new ESX kernel has an empty `ESX.PlayerData` at the first time a player logs in, and it takes some time to load and get it. PlayerData` is empty the first time a player logs in, and it takes some time to load and get it. Because this code doesn't throw an error in version 1.10.10.

**Comment by Mycroft-Studios** [comment]
![image](https://github.com/user-attachments/assets/2a8d114d-0f3c-40dc-950a-71a95608b0ce)
As u can see from the code.

**Comment by DyroS3** [comment]
```lua
local function init()
    if ESX.PlayerData.job.name == "xxx" then
        xxxxx()
    end
end

RegisterNetEvent('esx:playerLoaded', function(xPlayer, isNew, skin)
    init()
end)
```
Because I had code that was roughly structured like this, but in the new version it gives me the error

**Comment by Mycroft-Studios** [comment]
I will investigate

**Comment by Kenshiin13** [comment]
@DyroS3 Thanks for your report. This issue should be fixed in https://github.com/esx-framework/esx_core/pull/1480
