### ISSUE TITLE
[BUG] ES_Extended | Logs.lua

### ISSUE THREAD

**Issue by Luca8120** [esx-framework/esx_core#1471]
**Describe the bug**
The Logs Chat and Resources doesent work for me and the Logs Default and Test doesent work for me, or i couldt find anything that triggers these two. 

- Chat, Resource Logs doesent work

- Default, Test doesent work or i couldt find anything that triggers these

sry for my bad english, iam german.

**Debug Info (please complete the following information):**
 - OS: Windows Server 2022
 -  FiveM Artifact 11012
 - ESX Version: 1.11.2

**Comment by Mycroft-Studios** [comment]
User error
