### ISSUE TITLE
[BUG] esx_skin | error in F8 console

### ISSUE THREAD

**Issue by Luca8120** [esx-framework/esx_core#1474]
**Describe the bug**
got this error in F8 console when doing stuff in skin menu, which was given via /skin (ID)

**Debug Info (please complete the following information):**
 - OS: Windows Server 2022
 -  FiveM Artifact 11012
 - ESX Version: 1.11.2

[    531875] [b3095_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @esx_skin/client/modules/menu.lua:93: attempt to index a nil value (local 'component')^7
[    531875] [b3095_GTAProce]             MainThrd/ ^3> callback^7 (^5@esx_menu_default/client/main.lua^7:82)
[    531875] [b3095_GTAProce]             MainThrd/ ^1SCRIPT ERROR: ^7
[    531875] [b3095_GTAProce]             MainThrd/ ^3> callback^7 (^5@esx_menu_default/client/main.lua^7:82)
[    532172] [b3095_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @esx_skin/client/modules/menu.lua:93: attempt to index a nil value (local 'component')^7
[    532172] [b3095_GTAProce]             MainThrd/ ^3> callback^7 (^5@esx_menu_default/client/main.lua^7:82)
[    532172] [b3095_GTAProce]             MainThrd/ ^1SCRIPT ERROR: ^7
[    532172] [b3095_GTAProce]             MainThrd/ ^3> callback^7 (^5@esx_menu_default/client/main.lua^7:82)
[    532438] [b3095_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @esx_skin/client/modules/menu.lua:93: attempt to index a nil value (local 'component')^7
[    532438] [b3095_GTAProce]             MainThrd/ ^3> callback^7 (^5@esx_menu_default/client/main.lua^7:82)
[    532438] [b3095_GTAProce]             MainThrd/ ^1SCRIPT ERROR: ^7
[    532438] [b3095_GTAProce]             MainThrd/ ^3> callback^7 (^5@esx_menu_default/client/main.lua^7:82)
[    532688] [b3095_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @esx_skin/client/modules/menu.lua:93: attempt to index a nil value (local 'component')^7
[    532688] [b3095_GTAProce]             MainThrd/ ^3> callback^7 (^5@esx_menu_default/client/main.lua^7:82)
[    532688] [b3095_GTAProce]             MainThrd/ ^1SCRIPT ERROR: ^7
[    532688] [b3095_GTAProce]             MainThrd/ ^3> callback^7 (^5@esx_menu_default/client/main.lua^7:82)

Video: https://www.youtube.com/watch?v=xtndyT_JeH8

**Comment by Mycroft-Studios** [comment]
Already fixed in 1.12
