### ISSUE TITLE
[Bug] - es_extended - Issue

### ISSUE THREAD

**Issue by austincabler13** [esx-framework/esx_core#1519]
**Describe the bug**
`Build Error when I start the server (I changed the Build to the latest)`

**To Reproduce**
1. `TxAdmin`
2. `Live Console`
3. `Error`

**Expected behavior**
`No Error`

**Screenshots**
`03:55:28 PM [  script:es_extended] SCRIPT ERROR: @es_extended/server/main.lua:701: ESX Requires a minimum Artifact version of 10188, Please update your server.`
`03:55:28 PM [  script:es_extended] > fn (@es_extended/server/main.lua:701)`

**Debug Info (please complete the following information):**
 - `OS: (Windows)`
 -  `FiveM Artifact (Optional Download)`
 - `ESX Version: 1.11.4 (if its this Repo)`

**Additional context**
`Error in console`

**Comment by Mycroft-Studios** [comment]
User Error,
maybe read your own bug report:
> FiveM Artifact (Optional Download)

7290 is a smaller number than 10188

**Comment by austincabler13** [comment]
ya I Fixed it I downloaded the wrong Server so I need to do the steps again but at the time I thought it was build

**Comment by austincabler13** [comment]
and I was updating the wrong thing

**Comment by linus-ahlemeyer** [comment]
Were you following this by any chance? https://docs.qbcore.org/qbcore-documentation/guides/linux-installation

I am getting the same message, I put wget <latest-artifacts-url> and extract the archive but it doesn't matter which one I download ESX keeps giving me the same error message from your post above. What am I doing wrong?
