### ISSUE TITLE
[Bug] - esx_script - Issue

### ISSUE THREAD

**Issue by it-zeusx** [esx-framework/esx_core#1520]
**Describe the bug**
Hi! Recently, we discovered an issue with the esx:playerLoaded functionality on the client side while working with a customer.

We have implemented a multicharacter system that manages the player ped, and if the first player's model changes, esx:playerLoaded gets stuck in the following loop:

`
RegisterNetEvent("esx:playerLoaded", function(xPlayer, _, skin)
    ESX.PlayerData = xPlayer

    if not Config.Multichar then
        ESX.SpawnPlayer(skin, ESX.PlayerData.coords, function()
            TriggerEvent("esx:onPlayerSpawn")
            TriggerEvent("esx:restoreLoadout")
            TriggerServerEvent("esx:onPlayerSpawn")
            TriggerEvent("esx:loadingScreenOff")
            ShutdownLoadingScreen()
            ShutdownLoadingScreenNui()
        end)
    end

    while not DoesEntityExist(ESX.PlayerData.ped) do
        Wait(20)
    end

    ESX.PlayerLoaded = true
`

After debugging the issue, I found that the ESX.PlayerData.ped is only retrieved once during startup at client/modules/actions.lua. In our case, this causes the system to wait for a non-existent entity, resulting in an infinite loop.

**To Reproduce**
1. Wait for game to load
2. Change player model so the PlayerPedId native changes the initial value
3. Call loadESXPlayer

**Expected behavior**
In my opinion ESX.PlayerData.ped should be gathered once again at the call of esx:playerLoaded

**Screenshots**
-

**Debug Info (please complete the following information):**
 - OS: Windows
 -  FiveM Artifact 11536
 - ESX Version: 1.11.3

**Additional context**
None to add.

**Comment by Mycroft-Studios** [comment]
User error

**Comment by it-zeusx** [comment]
Could you clarify what you mean by "user error"?
