### ISSUE TITLE
[Bug] - es_extended - Issue

### ISSUE THREAD

**Issue by Akirabane** [esx-framework/esx_core#1530]
**Describe the bug**
Script error on server starting.

**To Reproduce**
1. download the latest artifact. Current version : 11895 (windows/linux)
2. Start your server (while having es_extended 1.11.4 hotfix correctly installed and ensured)
3. Going to the console and see this error : "cfx> [  script:es_extended] SCRIPT ERROR: @es_extended/server/main.lua:701: ESX Requires a minimum Artifact version of 10188, Please update your server."

**Expected behavior**
Script shouldn't ask for a minimum artifact version older than 10188 when you already have the latest one.

**Screenshots**
What's in the console :
cfx> [  script:es_extended] SCRIPT ERROR: @es_extended/server/main.lua:701: ESX Requires a minimum Artifact version of 10188, Please update your server.
[  script:es_extended] > fn (@es_extended/server/main.lua:701)
[  script:es_extended] SCRIPT ERROR: @es_extended/server/main.lua:701: ESX Requires a minimum Artifact version of 10188, Please update your server.

it repeats that message for like 100x times the nstop.

**Debug Info (please complete the following information):**
 - OS: Windows
 -  FiveM Artifact : 11895
 - ESX Version: 1.11.4 hotfix

**Comment by Akirabane** [comment]
Here are some images

![image](https://github.com/user-attachments/assets/9309d0ca-b654-4a78-bbbf-605e2e1fd2d7)
![image](https://github.com/user-attachments/assets/6fc056fb-70e1-47d4-a09e-364ddbf35bb6)

**Comment by Kenshiin13** [comment]
Hey @Akirabane,
can you please run the command `version` in your txAdmin live console and share a fullscreen screenshot of the output.

**Comment by Akirabane** [comment]
Did it, and looks like it outputs nothing.

![image](https://github.com/user-attachments/assets/08047e26-1f3d-4919-9fd1-d0b3140e0b37)

**Comment by Mycroft-Studios** [comment]
User error.
Dont use shitty unauthorised hostings that dont know what they are doing
