### ISSUE TITLE
[Bug] - Issue with skinchanger (1.11.4)

### ISSUE THREAD

**Issue by Brutuss** [esx-framework/esx_core#1537]
**Describe the bug**
When you go on duty in the cloakroom for example with the esx_policejob you open the cloakroom menu, click on "police wear" you are now on duty but still have you citizen clothes on. 

When loading an older skinchanger (before the remake) version 1.10.9 everything works as intended. 

There is no error in F8 console or in the server console when pushing the police wear button. 

Also tested this with the esx_ambulancejob same behavior. 

**To Reproduce**
1. Load the latest esx version (1.11.4) 
2. Start server end go to the cloakroom of the esx_policejob.
3. Open the cloakmenu and click on "Police waer".
4. No clothes change.

**Expected behavior**
What needs to happen is that the clothes should change as configured in the scripts. When using an older version of skinchanger it works.

**Screenshots**

**Debug Info (please complete the following information):**
 - OS: Windows
 - FiveM Artifact: 11859
 - ESX Version: 1.11.4

**Additional context**

**Comment by Mycroft-Studios** [comment]
1.12 will have a new method for this, so is not an issue.
this would also be an ESX skin issue, not skinchanger

**Comment by Brutuss** [comment]
Its an issue now with 1.11.4, but this problem will get fixed with version 1.12?

I can reproduce it when changing only the skinchanger script folder. The script that got a complete overhaul at version 1.11.0 Using the skinchanger before 1.11.0 there is no problem. 

esx_skin is also updated to the last version 1.11.4 if it is a esx_skin issue, whats the issue then and how to resolve this?
