### ISSUE TITLE
[Bug] - esx_society - Impossible to deposit money in the vaults

### ISSUE THREAD

**Issue by ShadowHazee** [esx-framework/esx_core#562]
**Describe the bug**
Impossible to deposit money in the vaults
The SQL table is in good condition.

**To Reproduce**

**Expected behavior**
![Capture d’écran 2022-10-11 155106](https://user-images.githubusercontent.com/115561916/195109737-dc56eb32-7086-4867-ae1e-e6d269bbb87c.png)

**Screenshots**

**Debug Info (please complete the following information):**
 - OS: ( Linux)
 -  FiveM Artifact 5948
 - ESX Version: 1.8.5 Legacy

**Additional context**

**Comment by giovihh** [comment]
same

**Comment by Benzo00** [comment]
will take a look into this!

**Comment by LeHazee** [comment]
Problem solved, I removed the dependencies in the manifests and added those of esx_society!

**Comment by lor3955** [comment]
Hey guys, 
someone have news? I have the same problem!!

**Comment by mr-capy** [comment]
it happed sometime with esx_vehicleshop too i temp fix it just adding society register line in policejob server side 
and i mention issue weeks ago
