### ISSUE TITLE
[Bug] - esx_extended - vehicle spawn

### ISSUE THREAD

**Issue by ghost** [esx-framework/esx_core#672]
**Describe the bug**
So everytime someone joins on my server and im already on it, and trying to spawn a vehicle it does not spawn
after the player joins, it gets spawned.

**To Reproduce**
1. Join on your server
2. let someone join your server
3. try to spawn a vehicle

**Expected behavior**
i expected that it works even if a player joins

**Screenshots**
no screenshots atm

**Debug Info (please complete the following information):**
 -  OS: Windows
 -  FiveM Artifact: 5963
 -  ESX Version: 1.8.5

**Comment by Gellipapa** [comment]
Hi! Do you use infinity onesync?
