### ISSUE TITLE
[Bug] - esx_policejob - vehicle shop

### ISSUE THREAD

**Issue by ghost** [esx-framework/esx_core#673]
**Describe the bug**
Thats the Error:
"[     63125] [b2372_GTAProce]             MainThrd/ error during NUI callback menu_submit: citizen:/scripting/lua/scheduler.lua:741: ^1SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:741: ^1SCRIPT ERROR: @esx_policejob/client/vehicle.lua:227: attempt to index a nil value (local 'props')^7"

**i tested it with addons**

**To Reproduce**
1. Go to the police station
2. Open the vehicle shop
3. try buying a vehicle

**Expected behavior**

**Screenshots**
no screenshots atm

**Debug Info (please complete the following information):**
 - OS: Windows
 -  FiveM Artifact: 5963
 - ESX Version: 1.8.5

**Comment by HirboSH** [comment]
> > Hey! It seems like the resource can't get the vehicle properties correctly. It happened only with a particular car or all of your custom car addons?
> 
> happens to all of our custom addons

Just tested the latest esx_policejob with a custom addon and it seems to work fine. Are you sure the car addon files aren't corrupted?
