### ISSUE TITLE
[Bug] - esx skin

### ISSUE THREAD

**Issue by KuMoNDev** [esx-framework/esx_core#689]
**Describe the bug**
Error in f8 and froze in the skin menu. When going in and out of the barbershop skinmenu to quick. 

**To Reproduce**

If I use the newest version of esx, and players go to barbershop, if they hit e and enter to fast or e and back space or walk out of the marker and back in and hit e and backspace  to quick they get this error. 

1. Go to barbershop
2. Press [E] to open barbershop
3. Hit backspace
4. Hit [E] again to open barbershop
5. If you do it a few times it will freeze skin menu  and throw the error below.

**Screenshots**

https://ibb.co/KqMzRXX

**Debug Info (please complete the following information):**
 - OS: ( Windows/Linux): windows
 -  FiveM Artifact: 6043
 - ESX Version: 1.8.5 (latest version

**Additional context**

**Comment by Gellipapa** [comment]
Hello! Which barber shop do you use because the newest one uses context menu?

**Comment by Mattt2283** [comment]
I use the newest barber shop, it uses context but it’s esx skin menu throwing the error not the barbershop I am just telling you what I did to get the error

**Comment by Mattt2283** [comment]
what i have found is to get it to do it everytime is that you just hit e and backspace quick 3 times then it freezes the whole skin menu.

**Comment by Cartman117** [comment]
Hi, I have something similar on 1.9.0

1. Go to barbershop
2. Press [E] to open barbershop
3. Hit Escape key
4. Hit [E] again to open barbershop
5. Can't escape or navigate in menu

I'm trying to find the issue and the fix.

**Comment by Cartman117** [comment]
Ok I figured it out, here is my PR to fix this #820
