### ISSUE TITLE
Listen to Lua Lint CI Pipeline and Resolve Issues

### ISSUE THREAD

**Issue by TasoOneAsia** [esx-framework/esx_core#695]
It's been a fair while since I've contributed anything ESX related, but I do take a look at this repository every now and then for 3rd party resource combability purposes. 

I've noticed that you have Lua linting CI configured that has been failing consistently for a while now. If I do need to make a contribution in the future, this is a little bit of turn-off for doing so. Actually listening to the linting tests would also go a long way in improving code quality, which has a historical reputation for being questionable.

Also, you may want to consider branch protection rules that require that CI passes prior to a merge to master.

**Comment by Gellipapa** [comment]
@TasoOneAsia It took us 2 years to get here, thank you for your comment and your work.
