### ISSUE TITLE
[Bug] - esx_taxi- Issue

### ISSUE THREAD

**Issue by bitpredator** [esx-framework/esx_core#752]
**Describe the bug**
Unable to open company inventory when using ox_inventory, ox_inventory version used 2.19.2

**Debug Info (please complete the following information):**
 - OS: ( Windows/Linux): Windows
 -  FiveM Artifact: 6136
 - ESX Version: 1.8.5

**Comment by Cluts** [comment]
Hello there! Thnx for previous answer to help me with esx_banking Objects stuff.
Btw, this is also happening to me, I can't use deposit/withdraw functions from Jobs Storage.
When I try to deposit it says "invalid quantity", and when I try to withdraw this happens:
![image](https://user-images.githubusercontent.com/6239217/208325061-d25fc195-f25c-4381-84a5-4872963e3270.png)

Items save with 0 x quantity so they just stuck there but I can't neither Deposit nor Withdraw them, I'm using ESX Inventory, not Ox Inv. I tried to disable Config.OxInventory                = ESX.GetConfig().OxInventory in config.lua but this didn't help at all.

**Comment by bitpredator** [comment]
> 
Hi, I've tried several inventories and the problem comes with all of them, the only solution I've found pending a fix is ​​to directly create a deposit/withdrawal with ox_inventory.

**Comment by Gellipapa** [comment]
> Hello there! Thnx for previous answer to help me with esx_banking Objects stuff. Btw, this is also happening to me, I can't use deposit/withdraw functions from Jobs Storage. When I try to deposit it says "invalid quantity", and when I try to withdraw this happens: ![image](https://user-images.githubusercontent.com/6239217/208325061-d25fc195-f25c-4381-84a5-4872963e3270.png)
> 
> Items save with 0 x quantity so they just stuck there but I can't neither Deposit nor Withdraw them, I'm using ESX Inventory, not Ox Inv. I tried to disable Config.OxInventory = ESX.GetConfig().OxInventory in config.lua but this didn't help at all.

Hi! We know about the bug, it is already fixed, we just need to test it and then the fix will be available. Your patience, please.
