### ISSUE TITLE
[Enhancement] - Update vehicle list to the latest patches

### ISSUE THREAD

**Issue by lexinor** [esx-framework/esx_core#817]
I think it would be a great improvment to update the vehicle list to the latest updates and why not add specials categories such as emergency and stuff.

**Comment by iSentrie** [comment]
emergencies buyable from civilian vehicle shop = good bye rp

**Comment by TheFantomas** [comment]
> emergencies buyable from civilian vehicle shop = good bye rp

This framework is not used only FOR ROLEPLAY :D But good argument :D

**Comment by iSentrie** [comment]
> > emergencies buyable from civilian vehicle shop = good bye rp
> 
> This framework is not used only FOR ROLEPLAY :D But good argument :D

This framework is clearly made for roleplay. Fulfilling emergency vehicles idea, will be necessary to take in mind this, which will be forced to make separate .sql files for that and I don't see the point doing that. 😉

**Comment by lexinor** [comment]
> emergencies buyable from civilian vehicle shop = good bye rp

Just be smart mate, you can just remove the "emergency" vehicles from the SQL request in esx_vehicleshop

**Comment by iSentrie** [comment]
Think about majority, not minority

**Comment by lexinor** [comment]
> Think about majority, not minority

Of course and that's why I said "why not" since it's not mandatory to do it so. Nevertheless, adding the latest vehicles is a must or atleast adding vehicles till the "Contract Updates"

**Comment by iSentrie** [comment]
this one has a little more added to the list, https://github.com/iLeaksy/fivem-vehicle-list/blob/main/FiveM%20-%20Vanilla%20Vehicles.sql

**Comment by Rav3n95** [comment]
If somebody done it, open a pr.
