### ISSUE TITLE
[Bug] - es_extended or esx_skin or skinchanger - Issue

### ISSUE THREAD

**Issue by GeKOfficiel** [esx-framework/esx_core#822]
Hello, I am currently having this problem when I arrive in game and after creating my identity, we cannot create my skin.

![image](https://user-images.githubusercontent.com/46930841/211173651-458e9c15-3833-41be-a614-a5118804f1b5.png)

 - OS: Windows
 -  FiveM Artifact 6195
 - ESX Version: 1.9.0

**Comment by ProSlayzz** [comment]
j ai le meme probleme

**Comment by Gellipapa** [comment]
@GeKOfficiel Update your full esx files to latest. We can't reproducate this error.
