### ISSUE TITLE
[Bug] - esx_mechanicjob Issue

### ISSUE THREAD

**Issue by JancsiOfficial** [esx-framework/esx_core#849]
Hi a problem is. I don't have a permission to garage or craft. I write another job grade name but it not worked. 
https://media.discordapp.net/attachments/783887871912312873/1066069221425033267/image.png

**Comment by CsokiHUN** [comment]
This error does not belong to this repo. open issue in [https://github.com/esx-framework/esx_mechanicjob](https://github.com/esx-framework/esx_mechanicjob)
