### ISSUE TITLE
[Bug]   @es_extended/server/modules/npwd.lua:35: No such export newPlayer in resource npwd  ,I am using whether ox_inventory supports updating  no Search  esx Inventory

### ISSUE THREAD

**Issue by Tompizza** [esx-framework/esx_core#870]
[  script:es_extended] SCRIPT ERROR: @es_extended/server/modules/npwd.lua:35: No such export newPlayer in resource npwd
[  script:es_extended] > loadESXPlayer (@es_extended/server/main.lua:298)
[  script:es_extended] > handler (@es_extended/server/main.lua:28)
[  script:es_extended] > <unknown> (@oxmysql/dist/build.js:22475)
[  script:es_extended] > processTicksAndRejections (node:internal/process/task_queues:96)
[  script:es_extended] [INFO] Player "Dddddd Dddddd" has connected to the server. ID: 1

I am using whether ox_inventory supports updating  no Search  esx Inventory

  npwd:setPhoneDisabled((ESX.SearchInventory('phone').count or 0) <= 0)

**Comment by CsokiHUN** [comment]
In the npwd config.json file, turn this on: [useResourceIntegration](https://github.com/project-error/npwd/blob/db3465b493fa1034e25a297826a23c9cf89e195d/config.json#L8)

**Comment by Rav3n95** [comment]
No respond
