### ISSUE TITLE
[Bug] - esx_identity - Cursor doesn't show in UI

### ISSUE THREAD

**Issue by TheHolyFire** [esx-framework/esx_core#881]
**Describe the bug**
Upon creating a char, it does not show the cursor in the UI

**To Reproduce**
1. Install esx_identity
2. join
3. See error

**Expected behavior**
I want to see a cursor to know where I am clicking

**Debug Info (please complete the following information):**
 - OS: Linux
 -  FiveM Artifact: 6230
 - ESX Version: 1.9.0

**Additional context**
1. When the User looks at the UI and the Script is restarted, it shows the cursor
but only if he looks at it
2. Restarting the script itself on start up does not fix the issue
3. setting the cursor in the style.css doesn't work
4. EnterCursorMode() does show the cursor, but disables the option to click the UI

**Comment by Unavarage** [comment]
You obviously use a custom loading screen right?

**Comment by Unavarage** [comment]
> **Describe the bug** Upon creating a char, it does not show the cursor in the UI
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Install esx_identity
> 2. join
> 3. See error
> 
> **Expected behavior** I want to see a cursor to know where I am clicking
> 
> **Debug Info (please complete the following information):**
> 
> * OS: Linux
> * FiveM Artifact: 6230
> * ESX Version: 1.9.0
> 
> **Additional context**
> 
> 1. When the User looks at the UI and the Script is restarted, it shows the cursor
>    but only if he looks at it
> 2. Restarting the script itself on start up does not fix the issue
> 3. setting the cursor in the style.css doesn't work
> 4. EnterCursorMode() does show the cursor, but disables the option to click the UI

You obviously use a custom loading screen right?

**Comment by laazaaroo** [comment]
Same problem, I have a custom loading screent, but it does not matter no?

**Comment by Unavarage** [comment]
Custom loading screen will affect the cursor to not show up because it already shows it on the loadingscreen.

**Comment by laazaaroo** [comment]
And is there any solution?

**Comment by TheHolyFire** [comment]
Based on what Mycroft said on a related [Discord Forum](https://discord.com/channels/513374574394474531/1069637900020490301)
"this issue is caused by having a bad loadingscreen
that does not use the correct functions for cursor"
still got no answer what the "correct" funtions are

**Comment by Unavarage** [comment]
> And is there any solution?



> Based on what Mycroft said on a related [Discord Forum](https://discord.com/channels/513374574394474531/1069637900020490301) "this issue is caused by having a bad loadingscreen that does not use the correct functions for cursor" still got no answer what the "correct" funtions are

So as for the cursor not showing on identity/register screen there is no solution, I tried to delete the line where the loadingscreen actually hides mouse after it loads into game, but can't seem to figure it out why because even if you delete those lines will show the cursor. As of now no solution only if you change your loadingscreen could be solved, but not every loadingscreen will work, so you need to try many of them.

**Comment by Mycroft-Studios** [comment]
> So as for the cursor not showing on identity/register screen there is no solution,
get a better loading screen. there is nothing ESX can do about this issue.

**Comment by Unavarage** [comment]
I think this thread can be closed.🤔

**Comment by TheHolyFire** [comment]
If this issue occurs:
Switch to a different Loading screen
