### ISSUE TITLE
[Bug] - es_extended - Translate error

### ISSUE THREAD

**Issue by FUst1ke** [esx-framework/esx_core#899]
**Describe the bug**
Hi, I have a problem which is most likely I don't have the exact translate and it gives me a error instead of a return or a print.

**To Reproduce**
 - no clue, if you try to call a translation which doesnt exist is should happen to you too.

**Expected behavior**
- everything but not an error, it should drop a print saying that this string does not exits or something.

**Screenshots**
SCRIPT ERROR: @es_extended/locale.lua:11: attempt to concatenate a nil value (local 'str')

**Debug Info (please complete the following information):**
 "version" is "FXServer-master SERVER v1.0.0.6230 win32"
 extended version: 1.9.0 

**Additional context**
have a nice day.

**Comment by MoskalykA** [comment]
Hi, it would be enough to use the string formatting system in Lua to solve the problem, that is: 
```lua 
print(("hello %s"):format("Arthur"))```

**Comment by Gellipapa** [comment]
#1026 This pr fix your problem. Thank you for report this issue.
