### ISSUE TITLE
[Feature Request] Add Starting Money not only starting bank

### ISSUE THREAD

**Issue by gabrieltr0008** [esx-framework/esx_core#905]
Currently you can only give starting players bank money, it would be better if you could also give normal money

**Comment by FilipeCuco** [comment]
lol just go in es_extended/config.lua and modify Config.StartingAccountMoney

**Comment by Mycroft-Studios** [comment]
> Currently you can only give starting players bank money, it would be better if you could also give normal money
it can give any valid account already.

**Comment by gabrieltr0008** [comment]
> > Currently you can only give starting players bank money, it would be better if you could also give normal money
> 
> it can give any valid account already.

No not for me its not working i can only give bank i already tried like this
Config.StartingAccountMoney 	= {bank = 50000, money = 25000}

**Comment by Mycroft-Studios** [comment]
> basically if we are using ox then its not working

then thats not an issue with esx...

**Comment by NikartikTheBear** [comment]
> basically if we are using ox then its not working

Ox treats money like an item, you would need to create something that gives the item when the player first join, but as mycroft said, that is not an issue with or from esx
