### ISSUE TITLE
[Bug] - es_extended - TPM Command

### ISSUE THREAD

**Issue by Pit2Fast** [esx-framework/esx_core#910]
When trying to use /tpm command the screen fades in and out but the player position is still the same

1. Create a marker on map
2. Use /tpm

I except my player to be teleported to the designated location 

 - OS: Windows
 -  FiveM Artifact: 6230
 - ESX Version: 1.9.2

**Comment by Mycroft-Studios** [comment]
make sure you have onesync infinity enabled

**Comment by Pit2Fast** [comment]
> make sure you have onesync infinity enabled

onesync infinity is enabled

**Comment by sleepyexe** [comment]
I fix that tpm problem with changing the whole ESX.PlayerData.ped to PlayerPedId() in esx tpm event

**Comment by Pit2Fast** [comment]
> I fix that tpm problem with changing the whole ESX.PlayerData.ped to PlayerPedId() in esx tpm event. I use fivem-appearance, so ESX.PlayerData.ped didn't change after changed clothes in fivem-appearance resources, so i decide to change ESX.PlayerData.ped to PlayerPedId(), i thought that ESX.PlayerData.ped is refreshed on specific event trigger, like PlayerLoaded, PlayerDead, PlayerSpawn, Player Setjob, etc. sorry for my bad english

Replacing ESX.PlayerData.ped with PlayerPedId() fixed the issue, thanks

**Comment by Rav3n95** [comment]
Just add ESX.SetPlayerData('ped', playerPed) under this line
https://github.com/esx-framework/esx_core/blob/0e53b30556f0b15b5a3be7592a09815a9404dcfa/%5Bcore%5D/es_extended/client/modules/actions.lua#L26
