### ISSUE TITLE
[Bug] - esx_policejob - Vehicle Garage Issue

### ISSUE THREAD

**Issue by Unavarage** [esx-framework/esx_core#923]
**Describe the bug**
If you go in the police garage and want to buy a new vehicle, you can view the vehicle, then press backspace and now you can't exit without restarting the script

**To Reproduce**
1. Go to 'Police Vehicle Garage'
2. Click on 'Auto Shop'
3. Select Any car and press view, while in view press backspace

**Expected behavior**
Should exit either way, if i press backspace should act as stop viewing

**Debug Info (please complete the following information):**
 - OS: Windows
 -  FiveM Artifact 6298
 - ESX Version: 1.9.3

**Comment by MoskalykA** [comment]
I would like to take care of this issue @Gellipapa

**Comment by Gellipapa** [comment]
> I would like to take care of this issue @Gellipapa

Who do you want to fix it?

**Comment by MoskalykA** [comment]
> > I would like to take care of this issue @Gellipapa
> 
> Who do you want to fix it?

Me

**Comment by Gellipapa** [comment]
Okey i assigned you, thank you for help.

**Comment by Unavarage** [comment]
> Well actually it does not seem to have any more problems, personally the return works perfectly

Did you find the problem of the non working backspace, that actually you have to click back because if you hit backspace the menu disappears and you can't exit without restarting the script?

**Comment by MoskalykA** [comment]
> > Well actually it does not seem to have any more problems, personally the return works perfectly
> 
> Did you find the problem of the non working backspace, that actually you have to click back because if you hit backspace the menu disappears and you can't exit without restarting the script?

Can you make a video of the problem? I have nothing on my side

**Comment by Gellipapa** [comment]
> > Well actually it does not seem to have any more problems, personally the return works perfectly
> 
> Did you find the problem of the non working backspace, that actually you have to click back because if you hit backspace the menu disappears and you can't exit without restarting the script?

I fixed this problem a while ago, test again and report back thanks.

**Comment by Unavarage** [comment]
> > > Well actually it does not seem to have any more problems, personally the return works perfectly
> > 
> > 
> > Did you find the problem of the non working backspace, that actually you have to click back because if you hit backspace the menu disappears and you can't exit without restarting the script?
> 
> I fixed this problem a while ago, test again and report back thanks.

OK, thanks I will test it and get back to you.

**Comment by Unavarage** [comment]
> > > Well actually it does not seem to have any more problems, personally the return works perfectly
> > 
> > 
> > Did you find the problem of the non working backspace, that actually you have to click back because if you hit backspace the menu disappears and you can't exit without restarting the script?
> 
> Can you make a video of the problem? I have nothing on my side

so where can I find the fixed policejob?

**Comment by MoskalykA** [comment]
> > > > Well actually it does not seem to have any more problems, personally the return works perfectly
> > > 
> > > 
> > > Did you find the problem of the non working backspace, that actually you have to click back because if you hit backspace the menu disappears and you can't exit without restarting the script?
> > 
> > 
> > Can you make a video of the problem? I have nothing on my side
> 
> so where can I find the fixed policejob?

here https://github.com/esx-framework/esx_policejob

**Comment by Unavarage** [comment]
> > > > > Well actually it does not seem to have any more problems, personally the return works perfectly
> > > > 
> > > > 
> > > > Did you find the problem of the non working backspace, that actually you have to click back because if you hit backspace the menu disappears and you can't exit without restarting the script?
> > > 
> > > 
> > > Can you make a video of the problem? I have nothing on my side
> > 
> > 
> > so where can I find the fixed policejob?
> 
> here https://github.com/esx-framework/esx_policejob

Yep, anything you've done to it, it's fixed. Thanks for the fast help.
