### ISSUE TITLE
[Feature] ESX Log

### ISSUE THREAD

**Issue by Gellipapa** [esx-framework/esx_core#975]
There should be a LOG system in es_extended that can be used to log normally formatted.

Log types: ERROR,WARN,INFO

Option for debug log, so if there is a log(true) in config, it logs only it should be a separate method.

Format should be something like [currentResourceName][logType]:message.

We also use colour. 

ERROR-red
WARN-orange
INFO-lightblue

**Comment by MoskalykA** [comment]
Hi, why not add the weather? Something like this

![image](https://user-images.githubusercontent.com/100430077/227654470-ce2f54e6-39af-453f-8ef9-017b16abe6ae.png)

**Comment by Mycroft-Studios** [comment]
> Hi, why not add the date?

because cfx add this when they generate logs

**Comment by Mycroft-Studios** [comment]
also this is basically already a thing...
