### ISSUE TITLE
[Feature Request] - esx_identity - Add locale

### ISSUE THREAD

**Issue by pelaoloko** [esx-framework/esx_core#988]
Locales['es'] = {
  ['show_active_character'] = 'Mostrar personaje actual',
  ['active_character'] = 'Personaje actual: %s',
  ['error_active_character'] = "Se produjo un error al recuperar tu nombre. Por favor contacta con un administrador",
  ['delete_character'] = 'Elimina tu personaje y crea uno nuevo',
  ['deleted_character'] = 'Tu personaje ha sido eliminado',
  ['error_delete_character'] = "Se produjo un error al eliminar tu personaje. Por favor contacta con un administrador",
  ['thank_you_for_registering'] = "Gracias por registrarte. Bienvenido a la ciudad",
  ['debug_xPlayer_get_first_name'] = "Devuelve tu nombre",
  ['debug_xPlayer_get_last_name'] = "Devuelve tu apellido",
  ['debug_xPlayer_get_full_name'] = "Devuelve tu nombre completo",
  ['debug_xPlayer_get_sex'] = "Devuelve tu sexo",
  ['debug_xPlayer_get_dob'] = "Devuelve tu fecha de nacimiento",
  ['debug_xPlayer_get_height'] = "Devuelve tu altura",
  ['error_debug_xPlayer_get_first_name'] = "Se produjo un error al recuperar tu nombre",
  ['error_debug_xPlayer_get_last_name'] = "Se produjo un error al recuperar tu apellido",
  ['error_debug_xPlayer_get_full_name'] = "Se produjo un error al recuperar tu nombre completo",
  ['error_debug_xPlayer_get_sex'] = "Se produjo un error al recuperar tu sexo",
  ['error_debug_xPlayer_get_dob'] = "Se produjo un error al recuperar tu fecha de nacimiento",
  ['error_debug_xPlayer_get_height'] = "Se produjo un error al recuperar tu altura",
  ['return_debug_xPlayer_get_first_name'] = "Nombre: %s",
  ['return_debug_xPlayer_get_last_name'] = "Apellido: %s",
  ['return_debug_xPlayer_get_full_name'] = "Nombre completo: %s",
  ['return_debug_xPlayer_get_sex'] = "Sexo: %s",
  ['return_debug_xPlayer_get_dob'] = "Fecha de nacimiento: %s",
  ['return_debug_xPlayer_get_height'] = "Altura: %s centímetros",
  ['data_incorrect'] = 'Datos introducidos de forma incorrecta. Inténtalo de nuevo',
  ['invalid_format'] = 'Datos con formato incorrecto. Inténtalo de nuevo',
  ['no_identifier'] = '¡Se ha producido un error al cargar tu personaje!\nCódigo de error: identifier-missing\n\nSe desconoce la causa de este error, no se pudo encontrar su identificador. Intentalo más tarde o informa de este problema al equipo administrativo del servidor',
  ['missing_identity'] = '¡Se ha producido un error al cargar tu personaje!\nCódigo de error: identity-missing\n\nParece que falta su identidad, intenta conectarte nuevamente',
  ['deleted_identity'] = 'Tu personaje ha sido borrado. Vuelva a iniciar sesión para crear un nuevo personaje',
  ['already_registered'] = 'Ya estás registrado.',
  ['invalid_firstname_format'] = 'Formato Inválido (Nombre): Inténtalo de nuevo.',
  ['invalid_lastname_format'] = 'Formato Inválido (Apellido): Inténtalo de nuevo.',
  ['invalid_dob_format'] = 'Formato Inválido (Fec. Nac.): Inténtalo de nuevo.',
  ['invalid_sex_format'] = 'Formato Inválido (Sexo): Inténtalo de nuevo.',
  ['invalid_height_format'] = 'Formato Inválido (Altura): Inténtalo de nuevo.'
}

**Comment by Benzo00** [comment]
^^
